import { ProvinceData } from "../../../packages/react-iran-maps/src/types/ProvinceData";

// Comprehensive mock data for all 31 Iranian provinces
export const mockProvinceData: ProvinceData[] = [
  {
    name: "تهران",
    count: 15000000,
    counties: [
      { name: "تهران", count: 8500000 },
      { name: "کرج", count: 2000000 },
      { name: "ورامین", count: 1200000 },
      { name: "شهریار", count: 800000 },
      { name: "اسلامشهر", count: 600000 },
      { name: "ملارد", count: 400000 },
      { name: "رباطکریم", count: 300000 },
      { name: "بهارستان", count: 250000 },
      { name: "پاکدشت", count: 200000 },
      { name: "دماوند", count: 150000 },
      { name: "فیروزکوه", count: 100000 },
      { name: "ری", count: 80000 },
      { name: "پردیس", count: 70000 },
      { name: "قدس", count: 60000 },
      { name: "فشم", count: 50000 },
    ],
  },
  {
    name: "اصفهان",
    count: 5120000,
    counties: [
      { name: "اصفهان", count: 2000000 },
      { name: "کاشان", count: 500000 },
      { name: "نجف‌آباد", count: 400000 },
      { name: "خمینی‌شهر", count: 300000 },
      { name: "شاهین‌شهر", count: 250000 },
      { name: "نطنز", count: 200000 },
      { name: "اردستان", count: 150000 },
      { name: "نایین", count: 120000 },
      { name: "تیران و کرون", count: 100000 },
      { name: "بوئین و میاندشت", count: 80000 },
      { name: "خوانسار", count: 70000 },
      { name: "فریدن", count: 60000 },
      { name: "فریدونشهر", count: 50000 },
      { name: "دهاقان", count: 40000 },
      { name: "مبارکه", count: 30000 },
      { name: "لنجان", count: 25000 },
      { name: "زرین‌شهر", count: 20000 },
      { name: "فولادشهر", count: 15000 },
      { name: "سپاهانشهر", count: 10000 },
      { name: "میمه", count: 8000 },
      { name: "شهرضا", count: 6000 },
      { name: "سمیرم", count: 5000 },
      { name: "دولت‌آباد", count: 4000 },
      { name: "باغ‌بهادران", count: 3000 },
    ],
  },
  {
    name: "فارس",
    count: 4850000,
    counties: [
      { name: "شیراز", count: 1900000 },
      { name: "کازرون", count: 300000 },
      { name: "مرودشت", count: 250000 },
      { name: "جهرم", count: 200000 },
      { name: "فسا", count: 150000 },
      { name: "داراب", count: 120000 },
      { name: "لارستان", count: 100000 },
      { name: "لامرد", count: 80000 },
      { name: "فراشبند", count: 60000 },
      { name: "قیر و کارزین", count: 50000 },
      { name: "کوار", count: 40000 },
      { name: "سپیدان", count: 35000 },
      { name: "ممسنی", count: 30000 },
      { name: "رستم", count: 25000 },
      { name: "بیضا", count: 20000 },
      { name: "ارسنجان", count: 15000 },
      { name: "استهبان", count: 12000 },
      { name: "نی‌ریز", count: 10000 },
      { name: "بوانات", count: 8000 },
      { name: "زرین‌دشت", count: 6000 },
      { name: "پاسارگاد", count: 5000 },
      { name: "خرم‌بید", count: 4000 },
      { name: "سروستان", count: 3000 },
      { name: "کوهگیلویه", count: 2000 },
      { name: "گراش", count: 1500 },
      { name: "خنج", count: 1000 },
      { name: "لامرد", count: 800 },
      { name: "مهر", count: 600 },
      { name: "فراشبند", count: 400 },
    ],
  },
  {
    name: "خوزستان",
    count: 4710000,
    counties: [
      { name: "اهواز", count: 1200000 },
      { name: "آبادان", count: 300000 },
      { name: "خرمشهر", count: 250000 },
      { name: "دزفول", count: 200000 },
      { name: "اندیمشک", count: 150000 },
      { name: "شوش", count: 120000 },
      { name: "شوشتر", count: 100000 },
      { name: "مسجدسلیمان", count: 80000 },
      { name: "ایذه", count: 60000 },
      { name: "باغ‌ملک", count: 50000 },
      { name: "رامهرمز", count: 40000 },
      { name: "هندیجان", count: 30000 },
      { name: "لالی", count: 25000 },
      { name: "باوی", count: 20000 },
      { name: "هویزه", count: 15000 },
      { name: "کارون", count: 12000 },
      { name: "بندر ماهشهر", count: 10000 },
      { name: "امیدیه", count: 8000 },
      { name: "بندر امام خمینی", count: 6000 },
      { name: "هندیجان", count: 5000 },
      { name: "لالی", count: 4000 },
      { name: "باوی", count: 3000 },
      { name: "هویزه", count: 2000 },
      { name: "کارون", count: 1500 },
      { name: "بندر ماهشهر", count: 1000 },
      { name: "امیدیه", count: 800 },
      { name: "بندر امام خمینی", count: 600 },
      { name: "هندیجان", count: 400 },
      { name: "لالی", count: 300 },
      { name: "باوی", count: 200 },
      { name: "هویزه", count: 150 },
      { name: "کارون", count: 100 },
    ],
  },
  {
    name: "خراسان رضوی",
    count: 6430000,
    counties: [
      { name: "مشهد", count: 3500000 },
      { name: "نیشابور", count: 500000 },
      { name: "سبزوار", count: 300000 },
      { name: "تربت‌حیدریه", count: 200000 },
      { name: "کاشمر", count: 150000 },
      { name: "تربت‌جام", count: 120000 },
      { name: "قوچان", count: 100000 },
      { name: "کلات", count: 80000 },
      { name: "فریمان", count: 60000 },
      { name: "مه ولات", count: 50000 },
      { name: "فیروزه", count: 40000 },
      { name: "بردسکن", count: 30000 },
      { name: "خلیل‌آباد", count: 25000 },
      { name: "کوهسرخ", count: 20000 },
      { name: "ریوش", count: 15000 },
      { name: "چناران", count: 12000 },
      { name: "کلات", count: 10000 },
      { name: "فریمان", count: 8000 },
      { name: "مه ولات", count: 6000 },
      { name: "فیروزه", count: 5000 },
      { name: "بردسکن", count: 4000 },
      { name: "خلیل‌آباد", count: 3000 },
      { name: "کوهسرخ", count: 2000 },
      { name: "ریوش", count: 1500 },
      { name: "چناران", count: 1000 },
      { name: "کلات", count: 800 },
      { name: "فریمان", count: 600 },
      { name: "مه ولات", count: 400 },
      { name: "فیروزه", count: 300 },
      { name: "بردسکن", count: 200 },
      { name: "خلیل‌آباد", count: 150 },
      { name: "کوهسرخ", count: 100 },
      { name: "ریوش", count: 80 },
      { name: "چناران", count: 60 },
    ],
  },
  {
    name: "آذربایجان شرقی",
    count: 3900000,
    counties: [
      { name: "تبریز", count: 1800000 },
      { name: "مراغه", count: 300000 },
      { name: "میانه", count: 200000 },
      { name: "اهر", count: 150000 },
      { name: "سراب", count: 120000 },
      { name: "شبستر", count: 100000 },
      { name: "مرند", count: 80000 },
      { name: "بناب", count: 60000 },
      { name: "آذرشهر", count: 50000 },
      { name: "هشترود", count: 40000 },
      { name: "کلیبر", count: 30000 },
      { name: "هریس", count: 25000 },
      { name: "ورزقان", count: 20000 },
      { name: "چاراویماق", count: 15000 },
      { name: "بستان‌آباد", count: 12000 },
      { name: "ملکان", count: 10000 },
      { name: "عجب‌شیر", count: 8000 },
      { name: "اسکو", count: 6000 },
      { name: "آذرشهر", count: 5000 },
      { name: "هشترود", count: 4000 },
      { name: "کلیبر", count: 3000 },
      { name: "هریس", count: 2000 },
      { name: "ورزقان", count: 1500 },
      { name: "چاراویماق", count: 1000 },
      { name: "بستان‌آباد", count: 800 },
      { name: "ملکان", count: 600 },
      { name: "عجب‌شیر", count: 400 },
      { name: "اسکو", count: 300 },
      { name: "آذرشهر", count: 200 },
      { name: "هشترود", count: 150 },
      { name: "کلیبر", count: 100 },
      { name: "هریس", count: 80 },
      { name: "ورزقان", count: 60 },
      { name: "چاراویماق", count: 40 },
      { name: "بستان‌آباد", count: 30 },
    ],
  },
  {
    name: "مازندران",
    count: 3280000,
    counties: [
      { name: "ساری", count: 500000 },
      { name: "بابل", count: 400000 },
      { name: "آمل", count: 300000 },
      { name: "قائمشهر", count: 250000 },
      { name: "بابلسر", count: 200000 },
      { name: "تنکابن", count: 150000 },
      { name: "نوشهر", count: 120000 },
      { name: "رامسر", count: 100000 },
      { name: "نکا", count: 80000 },
      { name: "فریدونکنار", count: 60000 },
      { name: "عباس‌آباد", count: 50000 },
      { name: "کلاردشت", count: 40000 },
      { name: "سوادکوه", count: 30000 },
      { name: "گلوگاه", count: 25000 },
      { name: "کیاسر", count: 20000 },
      { name: "سرخرود", count: 15000 },
      { name: "چالوس", count: 12000 },
      { name: "نوشهر", count: 10000 },
      { name: "رامسر", count: 8000 },
      { name: "نکا", count: 6000 },
      { name: "فریدونکنار", count: 5000 },
      { name: "عباس‌آباد", count: 4000 },
      { name: "کلاردشت", count: 3000 },
      { name: "سوادکوه", count: 2000 },
      { name: "گلوگاه", count: 1500 },
      { name: "کیاسر", count: 1000 },
      { name: "سرخرود", count: 800 },
      { name: "چالوس", count: 600 },
      { name: "نوشهر", count: 400 },
      { name: "رامسر", count: 300 },
      { name: "نکا", count: 200 },
      { name: "فریدونکنار", count: 150 },
      { name: "عباس‌آباد", count: 100 },
      { name: "کلاردشت", count: 80 },
      { name: "سوادکوه", count: 60 },
      { name: "گلوگاه", count: 40 },
      { name: "کیاسر", count: 30 },
      { name: "سرخرود", count: 20 },
      { name: "چالوس", count: 15 },
    ],
  },
  {
    name: "گیلان",
    count: 2530000,
    counties: [
      { name: "رشت", count: 800000 },
      { name: "بندر انزلی", count: 200000 },
      { name: "لاهیجان", count: 150000 },
      { name: "لنگرود", count: 120000 },
      { name: "رودسر", count: 100000 },
      { name: "فومن", count: 80000 },
      { name: "صومعه‌سرا", count: 60000 },
      { name: "آستارا", count: 50000 },
      { name: "طالش", count: 40000 },
      { name: "رودبار", count: 30000 },
      { name: "سیاهکل", count: 25000 },
      { name: "املش", count: 20000 },
      { name: "کلاچای", count: 15000 },
      { name: "چابکسر", count: 12000 },
      { name: "رامسر", count: 10000 },
      { name: "نکا", count: 8000 },
      { name: "فریدونکنار", count: 6000 },
      { name: "عباس‌آباد", count: 5000 },
      { name: "کلاردشت", count: 4000 },
      { name: "سوادکوه", count: 3000 },
      { name: "گلوگاه", count: 2000 },
      { name: "کیاسر", count: 1500 },
      { name: "سرخرود", count: 1000 },
      { name: "چالوس", count: 800 },
      { name: "نوشهر", count: 600 },
      { name: "رامسر", count: 400 },
      { name: "نکا", count: 300 },
      { name: "فریدونکنار", count: 200 },
      { name: "عباس‌آباد", count: 150 },
      { name: "کلاردشت", count: 100 },
      { name: "سوادکوه", count: 80 },
      { name: "گلوگاه", count: 60 },
      { name: "کیاسر", count: 40 },
      { name: "سرخرود", count: 30 },
      { name: "چالوس", count: 20 },
      { name: "نوشهر", count: 15 },
      { name: "رامسر", count: 10 },
      { name: "نکا", count: 8 },
      { name: "فریدونکنار", count: 6 },
      { name: "عباس‌آباد", count: 4 },
      { name: "کلاردشت", count: 3 },
      { name: "سوادکوه", count: 2 },
      { name: "گلوگاه", count: 1 },
    ],
  },
  {
    name: "کرمان",
    count: 3160000,
    counties: [
      { name: "کرمان", count: 800000 },
      { name: "رفسنجان", count: 200000 },
      { name: "جیرفت", count: 150000 },
      { name: "بم", count: 120000 },
      { name: "سیرجان", count: 100000 },
      { name: "شهربابک", count: 80000 },
      { name: "بردسیر", count: 60000 },
      { name: "رودبار جنوب", count: 50000 },
      { name: "عنبرآباد", count: 40000 },
      { name: "ریگان", count: 30000 },
      { name: "فهرج", count: 25000 },
      { name: "قلعه گنج", count: 20000 },
      { name: "فاریاب", count: 15000 },
      { name: "رودبار جنوب", count: 12000 },
      { name: "عنبرآباد", count: 10000 },
      { name: "ریگان", count: 8000 },
      { name: "فهرج", count: 6000 },
      { name: "قلعه گنج", count: 5000 },
      { name: "فاریاب", count: 4000 },
      { name: "رودبار جنوب", count: 3000 },
      { name: "عنبرآباد", count: 2000 },
      { name: "ریگان", count: 1500 },
      { name: "فهرج", count: 1000 },
      { name: "قلعه گنج", count: 800 },
      { name: "فاریاب", count: 600 },
      { name: "رودبار جنوب", count: 400 },
      { name: "عنبرآباد", count: 300 },
      { name: "ریگان", count: 200 },
      { name: "فهرج", count: 150 },
      { name: "قلعه گنج", count: 100 },
      { name: "فاریاب", count: 80 },
      { name: "رودبار جنوب", count: 60 },
      { name: "عنبرآباد", count: 40 },
      { name: "ریگان", count: 30 },
      { name: "فهرج", count: 20 },
      { name: "قلعه گنج", count: 15 },
      { name: "فاریاب", count: 10 },
      { name: "رودبار جنوب", count: 8 },
      { name: "عنبرآباد", count: 6 },
      { name: "ریگان", count: 4 },
      { name: "فهرج", count: 3 },
      { name: "قلعه گنج", count: 2 },
      { name: "فاریاب", count: 1 },
    ],
  },
  {
    name: "آذربایجان غربی",
    count: 3200000,
    counties: [
      { name: "ارومیه", count: 1000000 },
      { name: "خوی", count: 200000 },
      { name: "مرند", count: 150000 },
      { name: "مهاباد", count: 120000 },
      { name: "بوکان", count: 100000 },
      { name: "سلماس", count: 80000 },
      { name: "نقده", count: 60000 },
      { name: "میاندوآب", count: 50000 },
      { name: "شاهین‌دژ", count: 40000 },
      { name: "تکاب", count: 30000 },
      { name: "چالدران", count: 25000 },
      { name: "پیرانشهر", count: 20000 },
      { name: "سردشت", count: 15000 },
      { name: "بانه", count: 12000 },
      { name: "سقز", count: 10000 },
      { name: "مریوان", count: 8000 },
      { name: "قروه", count: 6000 },
      { name: "کامیاران", count: 5000 },
      { name: "سنندج", count: 4000 },
      { name: "دیواندره", count: 3000 },
      { name: "بیجار", count: 2000 },
      { name: "قروه", count: 1500 },
      { name: "کامیاران", count: 1000 },
      { name: "سنندج", count: 800 },
      { name: "دیواندره", count: 600 },
      { name: "بیجار", count: 400 },
      { name: "قروه", count: 300 },
      { name: "کامیاران", count: 200 },
      { name: "سنندج", count: 150 },
      { name: "دیواندره", count: 100 },
      { name: "بیجار", count: 80 },
      { name: "قروه", count: 60 },
      { name: "کامیاران", count: 40 },
      { name: "سنندج", count: 30 },
      { name: "دیواندره", count: 20 },
      { name: "بیجار", count: 15 },
      { name: "قروه", count: 10 },
      { name: "کامیاران", count: 8 },
      { name: "سنندج", count: 6 },
      { name: "دیواندره", count: 4 },
      { name: "بیجار", count: 3 },
      { name: "قروه", count: 2 },
      { name: "کامیاران", count: 1 },
    ],
  },
  {
    name: "لرستان",
    count: 1760000,
    counties: [
      { name: "خرم‌آباد", count: 500000 },
      { name: "بروجرد", count: 300000 },
      { name: "دورود", count: 200000 },
      { name: "کوهدشت", count: 150000 },
      { name: "الیگودرز", count: 120000 },
      { name: "نورآباد", count: 100000 },
      { name: "ازنا", count: 80000 },
      { name: "سلسله", count: 60000 },
      { name: "دلفان", count: 50000 },
      { name: "رومشکان", count: 40000 },
      { name: "پل‌دختر", count: 30000 },
      { name: "کوهدشت", count: 25000 },
      { name: "الیگودرز", count: 20000 },
      { name: "نورآباد", count: 15000 },
      { name: "ازنا", count: 12000 },
      { name: "سلسله", count: 10000 },
      { name: "دلفان", count: 8000 },
      { name: "رومشکان", count: 6000 },
      { name: "پل‌دختر", count: 5000 },
      { name: "کوهدشت", count: 4000 },
      { name: "الیگودرز", count: 3000 },
      { name: "نورآباد", count: 2000 },
      { name: "ازنا", count: 1500 },
      { name: "سلسله", count: 1000 },
      { name: "دلفان", count: 800 },
      { name: "رومشکان", count: 600 },
      { name: "پل‌دختر", count: 400 },
      { name: "کوهدشت", count: 300 },
      { name: "الیگودرز", count: 200 },
      { name: "نورآباد", count: 150 },
      { name: "ازنا", count: 100 },
      { name: "سلسله", count: 80 },
      { name: "دلفان", count: 60 },
      { name: "رومشکان", count: 40 },
      { name: "پل‌دختر", count: 30 },
      { name: "کوهدشت", count: 20 },
      { name: "الیگودرز", count: 15 },
      { name: "نورآباد", count: 10 },
      { name: "ازنا", count: 8 },
      { name: "سلسله", count: 6 },
      { name: "دلفان", count: 4 },
      { name: "رومشکان", count: 3 },
      { name: "پل‌دختر", count: 2 },
      { name: "کوهدشت", count: 1 },
    ],
  },
  {
    name: "کردستان",
    count: 1600000,
    counties: [
      { name: "سنندج", count: 500000 },
      { name: "مریوان", count: 200000 },
      { name: "سقز", count: 150000 },
      { name: "قروه", count: 120000 },
      { name: "کامیاران", count: 100000 },
      { name: "بیجار", count: 80000 },
      { name: "دیواندره", count: 60000 },
      { name: "سروآباد", count: 50000 },
      { name: "بانه", count: 40000 },
      { name: "سردشت", count: 30000 },
      { name: "پیرانشهر", count: 25000 },
      { name: "چالدران", count: 20000 },
      { name: "تکاب", count: 15000 },
      { name: "شاهین‌دژ", count: 12000 },
      { name: "میاندوآب", count: 10000 },
      { name: "نقده", count: 8000 },
      { name: "سلماس", count: 6000 },
      { name: "بوکان", count: 5000 },
      { name: "مهاباد", count: 4000 },
      { name: "مرند", count: 3000 },
      { name: "خوی", count: 2000 },
      { name: "ارومیه", count: 1500 },
      { name: "سلماس", count: 1000 },
      { name: "بوکان", count: 800 },
      { name: "مهاباد", count: 600 },
      { name: "مرند", count: 400 },
      { name: "خوی", count: 300 },
      { name: "ارومیه", count: 200 },
      { name: "سلماس", count: 150 },
      { name: "بوکان", count: 100 },
      { name: "مهاباد", count: 80 },
      { name: "مرند", count: 60 },
      { name: "خوی", count: 40 },
      { name: "ارومیه", count: 30 },
      { name: "سلماس", count: 20 },
      { name: "بوکان", count: 15 },
      { name: "مهاباد", count: 10 },
      { name: "مرند", count: 8 },
      { name: "خوی", count: 6 },
      { name: "ارومیه", count: 4 },
      { name: "سلماس", count: 3 },
      { name: "بوکان", count: 2 },
      { name: "مهاباد", count: 1 },
    ],
  },
  {
    name: "همدان",
    count: 1730000,
    counties: [
      { name: "همدان", count: 600000 },
      { name: "ملایر", count: 200000 },
      { name: "نهاوند", count: 150000 },
      { name: "کبودراهنگ", count: 120000 },
      { name: "بهار", count: 100000 },
      { name: "رزن", count: 80000 },
      { name: "فامنین", count: 60000 },
      { name: "اسدآباد", count: 50000 },
      { name: "تویسرکان", count: 40000 },
      { name: "بهار", count: 30000 },
      { name: "رزن", count: 25000 },
      { name: "فامنین", count: 20000 },
      { name: "اسدآباد", count: 15000 },
      { name: "تویسرکان", count: 12000 },
      { name: "بهار", count: 10000 },
      { name: "رزن", count: 8000 },
      { name: "فامنین", count: 6000 },
      { name: "اسدآباد", count: 5000 },
      { name: "تویسرکان", count: 4000 },
      { name: "بهار", count: 3000 },
      { name: "رزن", count: 2000 },
      { name: "فامنین", count: 1500 },
      { name: "اسدآباد", count: 1000 },
      { name: "تویسرکان", count: 800 },
      { name: "بهار", count: 600 },
      { name: "رزن", count: 400 },
      { name: "فامنین", count: 300 },
      { name: "اسدآباد", count: 200 },
      { name: "تویسرکان", count: 150 },
      { name: "بهار", count: 100 },
      { name: "رزن", count: 80 },
      { name: "فامنین", count: 60 },
      { name: "اسدآباد", count: 40 },
      { name: "تویسرکان", count: 30 },
      { name: "بهار", count: 20 },
      { name: "رزن", count: 15 },
      { name: "فامنین", count: 10 },
      { name: "اسدآباد", count: 8 },
      { name: "تویسرکان", count: 6 },
      { name: "بهار", count: 4 },
      { name: "رزن", count: 3 },
      { name: "فامنین", count: 2 },
      { name: "اسدآباد", count: 1 },
    ],
  },
  {
    name: "یزد",
    count: 1130000,
    counties: [
      { name: "یزد", count: 500000 },
      { name: "میبد", count: 100000 },
      { name: "اردکان", count: 80000 },
      { name: "بافق", count: 60000 },
      { name: "تفت", count: 50000 },
      { name: "ابرکوه", count: 40000 },
      { name: "هرات", count: 30000 },
      { name: "بهاباد", count: 25000 },
      { name: "خاتم", count: 20000 },
      { name: "مهریز", count: 15000 },
      { name: "اشکذر", count: 12000 },
      { name: "بهاباد", count: 10000 },
      { name: "خاتم", count: 8000 },
      { name: "مهریز", count: 6000 },
      { name: "اشکذر", count: 5000 },
      { name: "بهاباد", count: 4000 },
      { name: "خاتم", count: 3000 },
      { name: "مهریز", count: 2000 },
      { name: "اشکذر", count: 1500 },
      { name: "بهاباد", count: 1000 },
      { name: "خاتم", count: 800 },
      { name: "مهریز", count: 600 },
      { name: "اشکذر", count: 400 },
      { name: "بهاباد", count: 300 },
      { name: "خاتم", count: 200 },
      { name: "مهریز", count: 150 },
      { name: "اشکذر", count: 100 },
      { name: "بهاباد", count: 80 },
      { name: "خاتم", count: 60 },
      { name: "مهریز", count: 40 },
      { name: "اشکذر", count: 30 },
      { name: "بهاباد", count: 20 },
      { name: "خاتم", count: 15 },
      { name: "مهریز", count: 10 },
      { name: "اشکذر", count: 8 },
      { name: "بهاباد", count: 6 },
      { name: "خاتم", count: 4 },
      { name: "مهریز", count: 3 },
      { name: "اشکذر", count: 2 },
      { name: "بهاباد", count: 1 },
    ],
  },
  {
    name: "زنجان",
    count: 1050000,
    counties: [
      { name: "زنجان", count: 500000 },
      { name: "ابهر", count: 150000 },
      { name: "خدابنده", count: 100000 },
      { name: "ماهنشان", count: 80000 },
      { name: "ایجرود", count: 60000 },
      { name: "خرمدره", count: 50000 },
      { name: "سلطانیه", count: 40000 },
      { name: "طارم", count: 30000 },
      { name: "خدابنده", count: 25000 },
      { name: "ماهنشان", count: 20000 },
      { name: "ایجرود", count: 15000 },
      { name: "خرمدره", count: 12000 },
      { name: "سلطانیه", count: 10000 },
      { name: "طارم", count: 8000 },
      { name: "خدابنده", count: 6000 },
      { name: "ماهنشان", count: 5000 },
      { name: "ایجرود", count: 4000 },
      { name: "خرمدره", count: 3000 },
      { name: "سلطانیه", count: 2000 },
      { name: "طارم", count: 1500 },
      { name: "خدابنده", count: 1000 },
      { name: "ماهنشان", count: 800 },
      { name: "ایجرود", count: 600 },
      { name: "خرمدره", count: 400 },
      { name: "سلطانیه", count: 300 },
      { name: "طارم", count: 200 },
      { name: "خدابنده", count: 150 },
      { name: "ماهنشان", count: 100 },
      { name: "ایجرود", count: 80 },
      { name: "خرمدره", count: 60 },
      { name: "سلطانیه", count: 40 },
      { name: "طارم", count: 30 },
      { name: "خدابنده", count: 20 },
      { name: "ماهنشان", count: 15 },
      { name: "ایجرود", count: 10 },
      { name: "خرمدره", count: 8 },
      { name: "سلطانیه", count: 6 },
      { name: "طارم", count: 4 },
      { name: "خدابنده", count: 3 },
      { name: "ماهنشان", count: 2 },
      { name: "ایجرود", count: 1 },
    ],
  },
  {
    name: "مرکزی",
    count: 1420000,
    counties: [
      { name: "اراک", count: 600000 },
      { name: "ساوه", count: 200000 },
      { name: "محلات", count: 150000 },
      { name: "خمین", count: 120000 },
      { name: "دلیجان", count: 100000 },
      { name: "تفرش", count: 80000 },
      { name: "کمیجان", count: 60000 },
      { name: "آشتیان", count: 50000 },
      { name: "شازند", count: 40000 },
      { name: "زرندیه", count: 30000 },
      { name: "فراهان", count: 25000 },
      { name: "کمیجان", count: 20000 },
      { name: "آشتیان", count: 15000 },
      { name: "شازند", count: 12000 },
      { name: "زرندیه", count: 10000 },
      { name: "فراهان", count: 8000 },
      { name: "کمیجان", count: 6000 },
      { name: "آشتیان", count: 5000 },
      { name: "شازند", count: 4000 },
      { name: "زرندیه", count: 3000 },
      { name: "فراهان", count: 2000 },
      { name: "کمیجان", count: 1500 },
      { name: "آشتیان", count: 1000 },
      { name: "شازند", count: 800 },
      { name: "زرندیه", count: 600 },
      { name: "فراهان", count: 400 },
      { name: "کمیجان", count: 300 },
      { name: "آشتیان", count: 200 },
      { name: "شازند", count: 150 },
      { name: "زرندیه", count: 100 },
      { name: "فراهان", count: 80 },
      { name: "کمیجان", count: 60 },
      { name: "آشتیان", count: 40 },
      { name: "شازند", count: 30 },
      { name: "زرندیه", count: 20 },
      { name: "فراهان", count: 15 },
      { name: "کمیجان", count: 10 },
      { name: "آشتیان", count: 8 },
      { name: "شازند", count: 6 },
      { name: "زرندیه", count: 4 },
      { name: "فراهان", count: 3 },
      { name: "کمیجان", count: 2 },
      { name: "آشتیان", count: 1 },
    ],
  },
  {
    name: "هرمزگان",
    count: 1770000,
    counties: [
      { name: "بندرعباس", count: 600000 },
      { name: "میناب", count: 200000 },
      { name: "قشم", count: 150000 },
      { name: "کیش", count: 100000 },
      { name: "بندر لنگه", count: 80000 },
      { name: "جاسک", count: 60000 },
      { name: "رودان", count: 50000 },
      { name: "حاجی‌آباد", count: 40000 },
      { name: "پارسیان", count: 30000 },
      { name: "بستک", count: 25000 },
      { name: "خمیر", count: 20000 },
      { name: "سیریک", count: 15000 },
      { name: "رودان", count: 12000 },
      { name: "حاجی‌آباد", count: 10000 },
      { name: "پارسیان", count: 8000 },
      { name: "بستک", count: 6000 },
      { name: "خمیر", count: 5000 },
      { name: "سیریک", count: 4000 },
      { name: "رودان", count: 3000 },
      { name: "حاجی‌آباد", count: 2000 },
      { name: "پارسیان", count: 1500 },
      { name: "بستک", count: 1000 },
      { name: "خمیر", count: 800 },
      { name: "سیریک", count: 600 },
      { name: "رودان", count: 400 },
      { name: "حاجی‌آباد", count: 300 },
      { name: "پارسیان", count: 200 },
      { name: "بستک", count: 150 },
      { name: "خمیر", count: 100 },
      { name: "سیریک", count: 80 },
      { name: "رودان", count: 60 },
      { name: "حاجی‌آباد", count: 40 },
      { name: "پارسیان", count: 30 },
      { name: "بستک", count: 20 },
      { name: "خمیر", count: 15 },
      { name: "سیریک", count: 10 },
      { name: "رودان", count: 8 },
      { name: "حاجی‌آباد", count: 6 },
      { name: "پارسیان", count: 4 },
      { name: "بستک", count: 3 },
      { name: "خمیر", count: 2 },
      { name: "سیریک", count: 1 },
    ],
  },
  {
    name: "سیستان و بلوچستان",
    count: 2770000,
    counties: [
      { name: "زاهدان", count: 800000 },
      { name: "زابل", count: 200000 },
      { name: "چابهار", count: 150000 },
      { name: "ایرانشهر", count: 120000 },
      { name: "خاش", count: 100000 },
      { name: "سراوان", count: 80000 },
      { name: "نیک‌شهر", count: 60000 },
      { name: "کنارک", count: 50000 },
      { name: "دلگان", count: 40000 },
      { name: "فنوج", count: 30000 },
      { name: "قصرقند", count: 25000 },
      { name: "میرجاوه", count: 20000 },
      { name: "سیب و سوران", count: 15000 },
      { name: "راسک", count: 12000 },
      { name: "سرباز", count: 10000 },
      { name: "کنارک", count: 8000 },
      { name: "دلگان", count: 6000 },
      { name: "فنوج", count: 5000 },
      { name: "قصرقند", count: 4000 },
      { name: "میرجاوه", count: 3000 },
      { name: "سیب و سوران", count: 2000 },
      { name: "راسک", count: 1500 },
      { name: "سرباز", count: 1000 },
      { name: "کنارک", count: 800 },
      { name: "دلگان", count: 600 },
      { name: "فنوج", count: 400 },
      { name: "قصرقند", count: 300 },
      { name: "میرجاوه", count: 200 },
      { name: "سیب و سوران", count: 150 },
      { name: "راسک", count: 100 },
      { name: "سرباز", count: 80 },
      { name: "کنارک", count: 60 },
      { name: "دلگان", count: 40 },
      { name: "فنوج", count: 30 },
      { name: "قصرقند", count: 20 },
      { name: "میرجاوه", count: 15 },
      { name: "سیب و سوران", count: 10 },
      { name: "راسک", count: 8 },
      { name: "سرباز", count: 6 },
      { name: "کنارک", count: 4 },
      { name: "دلگان", count: 3 },
      { name: "فنوج", count: 2 },
      { name: "قصرقند", count: 1 },
    ],
  },
  {
    name: "گلستان",
    count: 1860000,
    counties: [
      { name: "گرگان", count: 400000 },
      { name: "آق‌قلا", count: 150000 },
      { name: "گنبد کاووس", count: 120000 },
      { name: "مینودشت", count: 100000 },
      { name: "کردکوی", count: 80000 },
      { name: "بندر گز", count: 60000 },
      { name: "ترکمن", count: 50000 },
      { name: "کلاله", count: 40000 },
      { name: "مراوه‌تپه", count: 30000 },
      { name: "فاضل‌آباد", count: 25000 },
      { name: "رامیان", count: 20000 },
      { name: "علی‌آباد کتول", count: 15000 },
      { name: "فاضل‌آباد", count: 12000 },
      { name: "رامیان", count: 10000 },
      { name: "علی‌آباد کتول", count: 8000 },
      { name: "فاضل‌آباد", count: 6000 },
      { name: "رامیان", count: 5000 },
      { name: "علی‌آباد کتول", count: 4000 },
      { name: "فاضل‌آباد", count: 3000 },
      { name: "رامیان", count: 2000 },
      { name: "علی‌آباد کتول", count: 1500 },
      { name: "فاضل‌آباد", count: 1000 },
      { name: "رامیان", count: 800 },
      { name: "علی‌آباد کتول", count: 600 },
      { name: "فاضل‌آباد", count: 400 },
      { name: "رامیان", count: 300 },
      { name: "علی‌آباد کتول", count: 200 },
      { name: "فاضل‌آباد", count: 150 },
      { name: "رامیان", count: 100 },
      { name: "علی‌آباد کتول", count: 80 },
      { name: "فاضل‌آباد", count: 60 },
      { name: "رامیان", count: 40 },
      { name: "علی‌آباد کتول", count: 30 },
      { name: "فاضل‌آباد", count: 20 },
      { name: "رامیان", count: 15 },
      { name: "علی‌آباد کتول", count: 10 },
      { name: "فاضل‌آباد", count: 8 },
      { name: "رامیان", count: 6 },
      { name: "علی‌آباد کتول", count: 4 },
      { name: "فاضل‌آباد", count: 3 },
      { name: "رامیان", count: 2 },
      { name: "علی‌آباد کتول", count: 1 },
    ],
  },
  {
    name: "قزوین",
    count: 1270000,
    counties: [
      { name: "قزوین", count: 500000 },
      { name: "تاکستان", count: 150000 },
      { name: "آبیک", count: 120000 },
      { name: "بوئین‌زهرا", count: 100000 },
      { name: "الوند", count: 80000 },
      { name: "آوج", count: 60000 },
      { name: "محمودآباد", count: 50000 },
      { name: "تاکستان", count: 40000 },
      { name: "آبیک", count: 30000 },
      { name: "بوئین‌زهرا", count: 25000 },
      { name: "الوند", count: 20000 },
      { name: "آوج", count: 15000 },
      { name: "محمودآباد", count: 12000 },
      { name: "تاکستان", count: 10000 },
      { name: "آبیک", count: 8000 },
      { name: "بوئین‌زهرا", count: 6000 },
      { name: "الوند", count: 5000 },
      { name: "آوج", count: 4000 },
      { name: "محمودآباد", count: 3000 },
      { name: "تاکستان", count: 2000 },
      { name: "آبیک", count: 1500 },
      { name: "بوئین‌زهرا", count: 1000 },
      { name: "الوند", count: 800 },
      { name: "آوج", count: 600 },
      { name: "محمودآباد", count: 400 },
      { name: "تاکستان", count: 300 },
      { name: "آبیک", count: 200 },
      { name: "بوئین‌زهرا", count: 150 },
      { name: "الوند", count: 100 },
      { name: "آوج", count: 80 },
      { name: "محمودآباد", count: 60 },
      { name: "تاکستان", count: 40 },
      { name: "آبیک", count: 30 },
      { name: "بوئین‌زهرا", count: 20 },
      { name: "الوند", count: 15 },
      { name: "آوج", count: 10 },
      { name: "محمودآباد", count: 8 },
      { name: "تاکستان", count: 6 },
      { name: "آبیک", count: 4 },
      { name: "بوئین‌زهرا", count: 3 },
      { name: "الوند", count: 2 },
      { name: "آوج", count: 1 },
    ],
  },
  {
    name: "قم",
    count: 1290000,
    counties: [
      { name: "قم", count: 1200000 },
      { name: "کهک", count: 50000 },
      { name: "سلفچگان", count: 30000 },
      { name: "کهک", count: 20000 },
      { name: "سلفچگان", count: 15000 },
      { name: "کهک", count: 10000 },
      { name: "سلفچگان", count: 8000 },
      { name: "کهک", count: 6000 },
      { name: "سلفچگان", count: 4000 },
      { name: "کهک", count: 3000 },
      { name: "سلفچگان", count: 2000 },
      { name: "کهک", count: 1500 },
      { name: "سلفچگان", count: 1000 },
      { name: "کهک", count: 800 },
      { name: "سلفچگان", count: 600 },
      { name: "کهک", count: 400 },
      { name: "سلفچگان", count: 300 },
      { name: "کهک", count: 200 },
      { name: "سلفچگان", count: 150 },
      { name: "کهک", count: 100 },
      { name: "سلفچگان", count: 80 },
      { name: "کهک", count: 60 },
      { name: "سلفچگان", count: 40 },
      { name: "کهک", count: 30 },
      { name: "سلفچگان", count: 20 },
      { name: "کهک", count: 15 },
      { name: "سلفچگان", count: 10 },
      { name: "کهک", count: 8 },
      { name: "سلفچگان", count: 6 },
      { name: "کهک", count: 4 },
      { name: "سلفچگان", count: 3 },
      { name: "کهک", count: 2 },
      { name: "سلفچگان", count: 1 },
    ],
  },
  {
    name: "سمنان",
    count: 702000,
    counties: [
      { name: "سمنان", count: 300000 },
      { name: "شاهرود", count: 200000 },
      { name: "دامغان", count: 100000 },
      { name: "گرمسار", count: 80000 },
      { name: "مهدیشهر", count: 60000 },
      { name: "بسطام", count: 40000 },
      { name: "میامی", count: 30000 },
      { name: "آرادان", count: 20000 },
      { name: "بسطام", count: 15000 },
      { name: "میامی", count: 12000 },
      { name: "آرادان", count: 10000 },
      { name: "بسطام", count: 8000 },
      { name: "میامی", count: 6000 },
      { name: "آرادان", count: 5000 },
      { name: "بسطام", count: 4000 },
      { name: "میامی", count: 3000 },
      { name: "آرادان", count: 2000 },
      { name: "بسطام", count: 1500 },
      { name: "میامی", count: 1000 },
      { name: "آرادان", count: 800 },
      { name: "بسطام", count: 600 },
      { name: "میامی", count: 400 },
      { name: "آرادان", count: 300 },
      { name: "بسطام", count: 200 },
      { name: "میامی", count: 150 },
      { name: "آرادان", count: 100 },
      { name: "بسطام", count: 80 },
      { name: "میامی", count: 60 },
      { name: "آرادان", count: 40 },
      { name: "بسطام", count: 30 },
      { name: "میامی", count: 20 },
      { name: "آرادان", count: 15 },
      { name: "بسطام", count: 10 },
      { name: "میامی", count: 8 },
      { name: "آرادان", count: 6 },
      { name: "بسطام", count: 4 },
      { name: "میامی", count: 3 },
      { name: "آرادان", count: 2 },
      { name: "بسطام", count: 1 },
    ],
  },
  {
    name: "کهگیلویه و بویراحمد",
    count: 713000,
    counties: [
      { name: "یاسوج", count: 200000 },
      { name: "دوگنبدان", count: 100000 },
      { name: "سی‌سخت", count: 80000 },
      { name: "مارگون", count: 60000 },
      { name: "بویراحمد", count: 50000 },
      { name: "دنا", count: 40000 },
      { name: "چرام", count: 30000 },
      { name: "لنده", count: 25000 },
      { name: "بهمئی", count: 20000 },
      { name: "مارگون", count: 15000 },
      { name: "بویراحمد", count: 12000 },
      { name: "دنا", count: 10000 },
      { name: "چرام", count: 8000 },
      { name: "لنده", count: 6000 },
      { name: "بهمئی", count: 5000 },
      { name: "مارگون", count: 4000 },
      { name: "بویراحمد", count: 3000 },
      { name: "دنا", count: 2000 },
      { name: "چرام", count: 1500 },
      { name: "لنده", count: 1000 },
      { name: "بهمئی", count: 800 },
      { name: "مارگون", count: 600 },
      { name: "بویراحمد", count: 400 },
      { name: "دنا", count: 300 },
      { name: "چرام", count: 200 },
      { name: "لنده", count: 150 },
      { name: "بهمئی", count: 100 },
      { name: "مارگون", count: 80 },
      { name: "بویراحمد", count: 60 },
      { name: "دنا", count: 40 },
      { name: "چرام", count: 30 },
      { name: "لنده", count: 20 },
      { name: "بهمئی", count: 15 },
      { name: "مارگون", count: 10 },
      { name: "بویراحمد", count: 8 },
      { name: "دنا", count: 6 },
      { name: "چرام", count: 4 },
      { name: "لنده", count: 3 },
      { name: "بهمئی", count: 2 },
      { name: "مارگون", count: 1 },
    ],
  },
  {
    name: "کرمانشاه",
    count: 1950000,
    counties: [
      { name: "کرمانشاه", count: 1000000 },
      { name: "اسلام‌آباد غرب", count: 200000 },
      { name: "کنگاور", count: 150000 },
      { name: "هرسین", count: 120000 },
      { name: "صحنه", count: 100000 },
      { name: "سنقر", count: 80000 },
      { name: "قصرشیرین", count: 60000 },
      { name: "گیلان غرب", count: 50000 },
      { name: "سرپل ذهاب", count: 40000 },
      { name: "ثلاث باباجانی", count: 30000 },
      { name: "جوانرود", count: 25000 },
      { name: "دالاهو", count: 20000 },
      { name: "سنقر", count: 15000 },
      { name: "قصرشیرین", count: 12000 },
      { name: "گیلان غرب", count: 10000 },
      { name: "سرپل ذهاب", count: 8000 },
      { name: "ثلاث باباجانی", count: 6000 },
      { name: "جوانرود", count: 5000 },
      { name: "دالاهو", count: 4000 },
      { name: "سنقر", count: 3000 },
      { name: "قصرشیرین", count: 2000 },
      { name: "گیلان غرب", count: 1500 },
      { name: "سرپل ذهاب", count: 1000 },
      { name: "ثلاث باباجانی", count: 800 },
      { name: "جوانرود", count: 600 },
      { name: "دالاهو", count: 400 },
      { name: "سنقر", count: 300 },
      { name: "قصرشیرین", count: 200 },
      { name: "گیلان غرب", count: 150 },
      { name: "سرپل ذهاب", count: 100 },
      { name: "ثلاث باباجانی", count: 80 },
      { name: "جوانرود", count: 60 },
      { name: "دالاهو", count: 40 },
      { name: "سنقر", count: 30 },
      { name: "قصرشیرین", count: 20 },
      { name: "گیلان غرب", count: 15 },
      { name: "سرپل ذهاب", count: 10 },
      { name: "ثلاث باباجانی", count: 8 },
      { name: "جوانرود", count: 6 },
      { name: "دالاهو", count: 4 },
      { name: "سنقر", count: 3 },
      { name: "قصرشیرین", count: 2 },
      { name: "گیلان غرب", count: 1 },
    ],
  },
  {
    name: "ایلام",
    count: 580000,
    counties: [
      { name: "ایلام", count: 200000 },
      { name: "دهلران", count: 100000 },
      { name: "آبدانان", count: 80000 },
      { name: "دره‌شهر", count: 60000 },
      { name: "مهران", count: 50000 },
      { name: "سرابله", count: 40000 },
      { name: "چرداول", count: 30000 },
      { name: "بدره", count: 25000 },
      { name: "ملکشاهی", count: 20000 },
      { name: "سرابله", count: 15000 },
      { name: "چرداول", count: 12000 },
      { name: "بدره", count: 10000 },
      { name: "ملکشاهی", count: 8000 },
      { name: "سرابله", count: 6000 },
      { name: "چرداول", count: 5000 },
      { name: "بدره", count: 4000 },
      { name: "ملکشاهی", count: 3000 },
      { name: "سرابله", count: 2000 },
      { name: "چرداول", count: 1500 },
      { name: "بدره", count: 1000 },
      { name: "ملکشاهی", count: 800 },
      { name: "سرابله", count: 600 },
      { name: "چرداول", count: 400 },
      { name: "بدره", count: 300 },
      { name: "ملکشاهی", count: 200 },
      { name: "سرابله", count: 150 },
      { name: "چرداول", count: 100 },
      { name: "بدره", count: 80 },
      { name: "ملکشاهی", count: 60 },
      { name: "سرابله", count: 40 },
      { name: "چرداول", count: 30 },
      { name: "بدره", count: 20 },
      { name: "ملکشاهی", count: 15 },
      { name: "سرابله", count: 10 },
      { name: "چرداول", count: 8 },
      { name: "بدره", count: 6 },
      { name: "ملکشاهی", count: 4 },
      { name: "سرابله", count: 3 },
      { name: "چرداول", count: 2 },
      { name: "بدره", count: 1 },
    ],
  },
  {
    name: "بوشهر",
    count: 1160000,
    counties: [
      { name: "بوشهر", count: 300000 },
      { name: "برازجان", count: 150000 },
      { name: "گناوه", count: 120000 },
      { name: "کنگان", count: 100000 },
      { name: "دشتستان", count: 80000 },
      { name: "تنگستان", count: 60000 },
      { name: "جم", count: 50000 },
      { name: "دیر", count: 40000 },
      { name: "عسلویه", count: 30000 },
      { name: "کنگان", count: 25000 },
      { name: "دشتستان", count: 20000 },
      { name: "تنگستان", count: 15000 },
      { name: "جم", count: 12000 },
      { name: "دیر", count: 10000 },
      { name: "عسلویه", count: 8000 },
      { name: "کنگان", count: 6000 },
      { name: "دشتستان", count: 5000 },
      { name: "تنگستان", count: 4000 },
      { name: "جم", count: 3000 },
      { name: "دیر", count: 2000 },
      { name: "عسلویه", count: 1500 },
      { name: "کنگان", count: 1000 },
      { name: "دشتستان", count: 800 },
      { name: "تنگستان", count: 600 },
      { name: "جم", count: 400 },
      { name: "دیر", count: 300 },
      { name: "عسلویه", count: 200 },
      { name: "کنگان", count: 150 },
      { name: "دشتستان", count: 100 },
      { name: "تنگستان", count: 80 },
      { name: "جم", count: 60 },
      { name: "دیر", count: 40 },
      { name: "عسلویه", count: 30 },
      { name: "کنگان", count: 20 },
      { name: "دشتستان", count: 15 },
      { name: "تنگستان", count: 10 },
      { name: "جم", count: 8 },
      { name: "دیر", count: 6 },
      { name: "عسلویه", count: 4 },
      { name: "کنگان", count: 3 },
      { name: "دشتستان", count: 2 },
      { name: "تنگستان", count: 1 },
    ],
  },
  {
    name: "چهارمحال و بختیاری",
    count: 947000,
    counties: [
      { name: "شهرکرد", count: 300000 },
      { name: "بروجن", count: 150000 },
      { name: "لردگان", count: 120000 },
      { name: "اردل", count: 100000 },
      { name: "فارسان", count: 80000 },
      { name: "کوهرنگ", count: 60000 },
      { name: "کیان", count: 50000 },
      { name: "بن", count: 40000 },
      { name: "سامان", count: 30000 },
      { name: "کوهرنگ", count: 25000 },
      { name: "کیان", count: 20000 },
      { name: "بن", count: 15000 },
      { name: "سامان", count: 12000 },
      { name: "کوهرنگ", count: 10000 },
      { name: "کیان", count: 8000 },
      { name: "بن", count: 6000 },
      { name: "سامان", count: 5000 },
      { name: "کوهرنگ", count: 4000 },
      { name: "کیان", count: 3000 },
      { name: "بن", count: 2000 },
      { name: "سامان", count: 1500 },
      { name: "کوهرنگ", count: 1000 },
      { name: "کیان", count: 800 },
      { name: "بن", count: 600 },
      { name: "سامان", count: 400 },
      { name: "کوهرنگ", count: 300 },
      { name: "کیان", count: 200 },
      { name: "بن", count: 150 },
      { name: "سامان", count: 100 },
      { name: "کوهرنگ", count: 80 },
      { name: "کیان", count: 60 },
      { name: "بن", count: 40 },
      { name: "سامان", count: 30 },
      { name: "کوهرنگ", count: 20 },
      { name: "کیان", count: 15 },
      { name: "بن", count: 10 },
      { name: "سامان", count: 8 },
      { name: "کوهرنگ", count: 6 },
      { name: "کیان", count: 4 },
      { name: "بن", count: 3 },
      { name: "سامان", count: 2 },
      { name: "کوهرنگ", count: 1 },
    ],
  },
  {
    name: "خراسان جنوبی",
    count: 768000,
    counties: [
      { name: "بیرجند", count: 250000 },
      { name: "قائن", count: 100000 },
      { name: "فردوس", count: 80000 },
      { name: "طبس", count: 60000 },
      { name: "نهبندان", count: 50000 },
      { name: "درمیان", count: 40000 },
      { name: "سرایان", count: 30000 },
      { name: "بشرویه", count: 25000 },
      { name: "خوسف", count: 20000 },
      { name: "سربیشه", count: 15000 },
      { name: "قائن", count: 12000 },
      { name: "فردوس", count: 10000 },
      { name: "طبس", count: 8000 },
      { name: "نهبندان", count: 6000 },
      { name: "درمیان", count: 5000 },
      { name: "سرایان", count: 4000 },
      { name: "بشرویه", count: 3000 },
      { name: "خوسف", count: 2000 },
      { name: "سربیشه", count: 1500 },
      { name: "قائن", count: 1000 },
      { name: "فردوس", count: 800 },
      { name: "طبس", count: 600 },
      { name: "نهبندان", count: 400 },
      { name: "درمیان", count: 300 },
      { name: "سرایان", count: 200 },
      { name: "بشرویه", count: 150 },
      { name: "خوسف", count: 100 },
      { name: "سربیشه", count: 80 },
      { name: "قائن", count: 60 },
      { name: "فردوس", count: 40 },
      { name: "طبس", count: 30 },
      { name: "نهبندان", count: 20 },
      { name: "درمیان", count: 15 },
      { name: "سرایان", count: 10 },
      { name: "بشرویه", count: 8 },
      { name: "خوسف", count: 6 },
      { name: "سربیشه", count: 4 },
      { name: "قائن", count: 3 },
      { name: "فردوس", count: 2 },
      { name: "طبس", count: 1 },
    ],
  },
  {
    name: "خراسان شمالی",
    count: 863000,
    counties: [
      { name: "بجنورد", count: 300000 },
      { name: "شیروان", count: 150000 },
      { name: "فاروج", count: 100000 },
      { name: "اسفراین", count: 80000 },
      { name: "مانه و سملقان", count: 60000 },
      { name: "رازوجرگلان", count: 50000 },
      { name: "جاجرم", count: 40000 },
      { name: "فاروج", count: 30000 },
      { name: "اسفراین", count: 25000 },
      { name: "مانه و سملقان", count: 20000 },
      { name: "رازوجرگلان", count: 15000 },
      { name: "جاجرم", count: 12000 },
      { name: "فاروج", count: 10000 },
      { name: "اسفراین", count: 8000 },
      { name: "مانه و سملقان", count: 6000 },
      { name: "رازوجرگلان", count: 5000 },
      { name: "جاجرم", count: 4000 },
      { name: "فاروج", count: 3000 },
      { name: "اسفراین", count: 2000 },
      { name: "مانه و سملقان", count: 1500 },
      { name: "رازوجرگلان", count: 1000 },
      { name: "جاجرم", count: 800 },
      { name: "فاروج", count: 600 },
      { name: "اسفراین", count: 400 },
      { name: "مانه و سملقان", count: 300 },
      { name: "رازوجرگلان", count: 200 },
      { name: "جاجرم", count: 150 },
      { name: "فاروج", count: 100 },
      { name: "اسفراین", count: 80 },
      { name: "مانه و سملقان", count: 60 },
      { name: "رازوجرگلان", count: 40 },
      { name: "جاجرم", count: 30 },
      { name: "فاروج", count: 20 },
      { name: "اسفراین", count: 15 },
      { name: "مانه و سملقان", count: 10 },
      { name: "رازوجرگلان", count: 8 },
      { name: "جاجرم", count: 6 },
      { name: "فاروج", count: 4 },
      { name: "اسفراین", count: 3 },
      { name: "مانه و سملقان", count: 2 },
      { name: "رازوجرگلان", count: 1 },
    ],
  },
  {
    name: "اردبیل",
    count: 1290000,
    counties: [
      { name: "اردبیل", count: 500000 },
      { name: "پارس‌آباد", count: 200000 },
      { name: "خلخال", count: 150000 },
      { name: "مشگین‌شهر", count: 120000 },
      { name: "گرمی", count: 100000 },
      { name: "بیله‌سوار", count: 80000 },
      { name: "کوثر", count: 60000 },
      { name: "سرعین", count: 50000 },
      { name: "نمین", count: 40000 },
      { name: "گرمی", count: 30000 },
      { name: "بیله‌سوار", count: 25000 },
      { name: "کوثر", count: 20000 },
      { name: "سرعین", count: 15000 },
      { name: "نمین", count: 12000 },
      { name: "گرمی", count: 10000 },
      { name: "بیله‌سوار", count: 8000 },
      { name: "کوثر", count: 6000 },
      { name: "سرعین", count: 5000 },
      { name: "نمین", count: 4000 },
      { name: "گرمی", count: 3000 },
      { name: "بیله‌سوار", count: 2000 },
      { name: "کوثر", count: 1500 },
      { name: "سرعین", count: 1000 },
      { name: "نمین", count: 800 },
      { name: "گرمی", count: 600 },
      { name: "بیله‌سوار", count: 400 },
      { name: "کوثر", count: 300 },
      { name: "سرعین", count: 200 },
      { name: "نمین", count: 150 },
      { name: "گرمی", count: 100 },
      { name: "بیله‌سوار", count: 80 },
      { name: "کوثر", count: 60 },
      { name: "سرعین", count: 40 },
      { name: "نمین", count: 30 },
      { name: "گرمی", count: 20 },
      { name: "بیله‌سوار", count: 15 },
      { name: "کوثر", count: 10 },
      { name: "سرعین", count: 8 },
      { name: "نمین", count: 6 },
      { name: "گرمی", count: 4 },
      { name: "بیله‌سوار", count: 3 },
      { name: "کوثر", count: 2 },
      { name: "سرعین", count: 1 },
    ],
  },
  {
    name: "البرز",
    count: 2710000,
    counties: [
      { name: "کرج", count: 2000000 },
      { name: "نظرآباد", count: 200000 },
      { name: "ساوجبلاغ", count: 150000 },
      { name: "طالقان", count: 100000 },
      { name: "فردیس", count: 80000 },
      { name: "ماهدشت", count: 60000 },
      { name: "هشتگرد", count: 50000 },
      { name: "نظرآباد", count: 40000 },
      { name: "ساوجبلاغ", count: 30000 },
      { name: "طالقان", count: 25000 },
      { name: "فردیس", count: 20000 },
      { name: "ماهدشت", count: 15000 },
      { name: "هشتگرد", count: 12000 },
      { name: "نظرآباد", count: 10000 },
      { name: "ساوجبلاغ", count: 8000 },
      { name: "طالقان", count: 6000 },
      { name: "فردیس", count: 5000 },
      { name: "ماهدشت", count: 4000 },
      { name: "هشتگرد", count: 3000 },
      { name: "نظرآباد", count: 2000 },
      { name: "ساوجبلاغ", count: 1500 },
      { name: "طالقان", count: 1000 },
      { name: "فردیس", count: 800 },
      { name: "ماهدشت", count: 600 },
      { name: "هشتگرد", count: 400 },
      { name: "نظرآباد", count: 300 },
      { name: "ساوجبلاغ", count: 200 },
      { name: "طالقان", count: 150 },
      { name: "فردیس", count: 100 },
      { name: "ماهدشت", count: 80 },
      { name: "هشتگرد", count: 60 },
      { name: "نظرآباد", count: 40 },
      { name: "ساوجبلاغ", count: 30 },
      { name: "طالقان", count: 20 },
      { name: "فردیس", count: 15 },
      { name: "ماهدشت", count: 10 },
      { name: "هشتگرد", count: 8 },
      { name: "نظرآباد", count: 6 },
      { name: "ساوجبلاغ", count: 4 },
      { name: "طالقان", count: 3 },
      { name: "فردیس", count: 2 },
      { name: "ماهدشت", count: 1 },
    ],
  },
];

// Helper function to get province data by Persian name
export function getProvinceDataByName(
  persianName: string
): ProvinceData | undefined {
  return mockProvinceData.find((province) => province.name === persianName);
}

// Helper function to get all province names
export function getAllProvinceNames(): string[] {
  return mockProvinceData.map((province) => province.name);
}

// Helper function to get total population
export function getTotalPopulation(): number {
  return mockProvinceData.reduce(
    (total, province) => total + province.count,
    0
  );
}
