import { ProvinceData } from "../../../packages/react-iran-maps/src/types/ProvinceData";

// Comprehensive mock data for all 31 Iranian provinces
export const mockProvinceData: ProvinceData[] = [
  {
    name: "تهران",
    value: 15000000,
    counties: [
      { name: "تهران", value: 8500000 },
      { name: "کرج", value: 2000000 },
      { name: "ورامین", value: 1200000 },
      { name: "شهریار", value: 800000 },
      { name: "اسلامشهر", value: 600000 },
      { name: "ملارد", value: 400000 },
      { name: "رباطکریم", value: 300000 },
      { name: "بهارستان", value: 250000 },
      { name: "پاکدشت", value: 200000 },
      { name: "دماوند", value: 150000 },
      { name: "فیروزکوه", value: 100000 },
      { name: "ری", value: 80000 },
      { name: "پردیس", value: 70000 },
      { name: "قدس", value: 60000 },
      { name: "فشم", value: 50000 },
    ],
  },
  {
    name: "اصفهان",
    value: 5120000,
    counties: [
      { name: "اصفهان", value: 2000000 },
      { name: "کاشان", value: 500000 },
      { name: "نجف‌آباد", value: 400000 },
      { name: "خمینی‌شهر", value: 300000 },
      { name: "شاهین‌شهر", value: 250000 },
      { name: "نطنز", value: 200000 },
      { name: "اردستان", value: 150000 },
      { name: "نایین", value: 120000 },
      { name: "تیران و کرون", value: 100000 },
      { name: "بوئین و میاندشت", value: 80000 },
      { name: "خوانسار", value: 70000 },
      { name: "فریدن", value: 60000 },
      { name: "فریدونشهر", value: 50000 },
      { name: "دهاقان", value: 40000 },
      { name: "مبارکه", value: 30000 },
      { name: "لنجان", value: 25000 },
      { name: "زرین‌شهر", value: 20000 },
      { name: "فولادشهر", value: 15000 },
      { name: "سپاهانشهر", value: 10000 },
      { name: "میمه", value: 8000 },
      { name: "شهرضا", value: 6000 },
      { name: "سمیرم", value: 5000 },
      { name: "دولت‌آباد", value: 4000 },
      { name: "باغ‌بهادران", value: 3000 },
    ],
  },
  {
    name: "فارس",
    value: 4850000,
    counties: [
      { name: "شیراز", value: 1900000 },
      { name: "کازرون", value: 300000 },
      { name: "مرودشت", value: 250000 },
      { name: "جهرم", value: 200000 },
      { name: "فسا", value: 150000 },
      { name: "داراب", value: 120000 },
      { name: "لارستان", value: 100000 },
      { name: "لامرد", value: 80000 },
      { name: "فراشبند", value: 60000 },
      { name: "قیر و کارزین", value: 50000 },
      { name: "کوار", value: 40000 },
      { name: "سپیدان", value: 35000 },
      { name: "ممسنی", value: 30000 },
      { name: "رستم", value: 25000 },
      { name: "بیضا", value: 20000 },
      { name: "ارسنجان", value: 15000 },
      { name: "استهبان", value: 12000 },
      { name: "نی‌ریز", value: 10000 },
      { name: "بوانات", value: 8000 },
      { name: "زرین‌دشت", value: 6000 },
      { name: "پاسارگاد", value: 5000 },
      { name: "خرم‌بید", value: 4000 },
      { name: "سروستان", value: 3000 },
      { name: "کوهگیلویه", value: 2000 },
      { name: "گراش", value: 1500 },
      { name: "خنج", value: 1000 },
      { name: "لامرد", value: 800 },
      { name: "مهر", value: 600 },
      { name: "فراشبند", value: 400 },
    ],
  },
  {
    name: "خوزستان",
    value: 4710000,
    counties: [
      { name: "اهواز", value: 1200000 },
      { name: "آبادان", value: 300000 },
      { name: "خرمشهر", value: 250000 },
      { name: "دزفول", value: 200000 },
      { name: "اندیمشک", value: 150000 },
      { name: "شوش", value: 120000 },
      { name: "شوشتر", value: 100000 },
      { name: "مسجدسلیمان", value: 80000 },
      { name: "ایذه", value: 60000 },
      { name: "باغ‌ملک", value: 50000 },
      { name: "رامهرمز", value: 40000 },
      { name: "هندیجان", value: 30000 },
      { name: "لالی", value: 25000 },
      { name: "باوی", value: 20000 },
      { name: "هویزه", value: 15000 },
      { name: "کارون", value: 12000 },
      { name: "بندر ماهشهر", value: 10000 },
      { name: "امیدیه", value: 8000 },
      { name: "بندر امام خمینی", value: 6000 },
      { name: "هندیجان", value: 5000 },
      { name: "لالی", value: 4000 },
      { name: "باوی", value: 3000 },
      { name: "هویزه", value: 2000 },
      { name: "کارون", value: 1500 },
      { name: "بندر ماهشهر", value: 1000 },
      { name: "امیدیه", value: 800 },
      { name: "بندر امام خمینی", value: 600 },
      { name: "هندیجان", value: 400 },
      { name: "لالی", value: 300 },
      { name: "باوی", value: 200 },
      { name: "هویزه", value: 150 },
      { name: "کارون", value: 100 },
    ],
  },
  {
    name: "خراسان رضوی",
    value: 6430000,
    counties: [
      { name: "مشهد", value: 3500000 },
      { name: "نیشابور", value: 500000 },
      { name: "سبزوار", value: 300000 },
      { name: "تربت‌حیدریه", value: 200000 },
      { name: "کاشمر", value: 150000 },
      { name: "تربت‌جام", value: 120000 },
      { name: "قوچان", value: 100000 },
      { name: "کلات", value: 80000 },
      { name: "فریمان", value: 60000 },
      { name: "مه ولات", value: 50000 },
      { name: "فیروزه", value: 40000 },
      { name: "بردسکن", value: 30000 },
      { name: "خلیل‌آباد", value: 25000 },
      { name: "کوهسرخ", value: 20000 },
      { name: "ریوش", value: 15000 },
      { name: "چناران", value: 12000 },
      { name: "کلات", value: 10000 },
      { name: "فریمان", value: 8000 },
      { name: "مه ولات", value: 6000 },
      { name: "فیروزه", value: 5000 },
      { name: "بردسکن", value: 4000 },
      { name: "خلیل‌آباد", value: 3000 },
      { name: "کوهسرخ", value: 2000 },
      { name: "ریوش", value: 1500 },
      { name: "چناران", value: 1000 },
      { name: "کلات", value: 800 },
      { name: "فریمان", value: 600 },
      { name: "مه ولات", value: 400 },
      { name: "فیروزه", value: 300 },
      { name: "بردسکن", value: 200 },
      { name: "خلیل‌آباد", value: 150 },
      { name: "کوهسرخ", value: 100 },
      { name: "ریوش", value: 80 },
      { name: "چناران", value: 60 },
    ],
  },
  {
    name: "آذربایجان شرقی",
    value: 3900000,
    counties: [
      { name: "تبریز", value: 1800000 },
      { name: "مراغه", value: 300000 },
      { name: "میانه", value: 200000 },
      { name: "اهر", value: 150000 },
      { name: "سراب", value: 120000 },
      { name: "شبستر", value: 100000 },
      { name: "مرند", value: 80000 },
      { name: "بناب", value: 60000 },
      { name: "آذرشهر", value: 50000 },
      { name: "هشترود", value: 40000 },
      { name: "کلیبر", value: 30000 },
      { name: "هریس", value: 25000 },
      { name: "ورزقان", value: 20000 },
      { name: "چاراویماق", value: 15000 },
      { name: "بستان‌آباد", value: 12000 },
      { name: "ملکان", value: 10000 },
      { name: "عجب‌شیر", value: 8000 },
      { name: "اسکو", value: 6000 },
      { name: "آذرشهر", value: 5000 },
      { name: "هشترود", value: 4000 },
      { name: "کلیبر", value: 3000 },
      { name: "هریس", value: 2000 },
      { name: "ورزقان", value: 1500 },
      { name: "چاراویماق", value: 1000 },
      { name: "بستان‌آباد", value: 800 },
      { name: "ملکان", value: 600 },
      { name: "عجب‌شیر", value: 400 },
      { name: "اسکو", value: 300 },
      { name: "آذرشهر", value: 200 },
      { name: "هشترود", value: 150 },
      { name: "کلیبر", value: 100 },
      { name: "هریس", value: 80 },
      { name: "ورزقان", value: 60 },
      { name: "چاراویماق", value: 40 },
      { name: "بستان‌آباد", value: 30 },
    ],
  },
  {
    name: "مازندران",
    value: 3280000,
    counties: [
      { name: "ساری", value: 500000 },
      { name: "بابل", value: 400000 },
      { name: "آمل", value: 300000 },
      { name: "قائمشهر", value: 250000 },
      { name: "بابلسر", value: 200000 },
      { name: "تنکابن", value: 150000 },
      { name: "نوشهر", value: 120000 },
      { name: "رامسر", value: 100000 },
      { name: "نکا", value: 80000 },
      { name: "فریدونکنار", value: 60000 },
      { name: "عباس‌آباد", value: 50000 },
      { name: "کلاردشت", value: 40000 },
      { name: "سوادکوه", value: 30000 },
      { name: "گلوگاه", value: 25000 },
      { name: "کیاسر", value: 20000 },
      { name: "سرخرود", value: 15000 },
      { name: "چالوس", value: 12000 },
      { name: "نوشهر", value: 10000 },
      { name: "رامسر", value: 8000 },
      { name: "نکا", value: 6000 },
      { name: "فریدونکنار", value: 5000 },
      { name: "عباس‌آباد", value: 4000 },
      { name: "کلاردشت", value: 3000 },
      { name: "سوادکوه", value: 2000 },
      { name: "گلوگاه", value: 1500 },
      { name: "کیاسر", value: 1000 },
      { name: "سرخرود", value: 800 },
      { name: "چالوس", value: 600 },
      { name: "نوشهر", value: 400 },
      { name: "رامسر", value: 300 },
      { name: "نکا", value: 200 },
      { name: "فریدونکنار", value: 150 },
      { name: "عباس‌آباد", value: 100 },
      { name: "کلاردشت", value: 80 },
      { name: "سوادکوه", value: 60 },
      { name: "گلوگاه", value: 40 },
      { name: "کیاسر", value: 30 },
      { name: "سرخرود", value: 20 },
      { name: "چالوس", value: 15 },
    ],
  },
  {
    name: "گیلان",
    value: 2530000,
    counties: [
      { name: "رشت", value: 800000 },
      { name: "بندر انزلی", value: 200000 },
      { name: "لاهیجان", value: 150000 },
      { name: "لنگرود", value: 120000 },
      { name: "رودسر", value: 100000 },
      { name: "فومن", value: 80000 },
      { name: "صومعه‌سرا", value: 60000 },
      { name: "آستارا", value: 50000 },
      { name: "طالش", value: 40000 },
      { name: "رودبار", value: 30000 },
      { name: "سیاهکل", value: 25000 },
      { name: "املش", value: 20000 },
      { name: "کلاچای", value: 15000 },
      { name: "چابکسر", value: 12000 },
      { name: "رامسر", value: 10000 },
      { name: "نکا", value: 8000 },
      { name: "فریدونکنار", value: 6000 },
      { name: "عباس‌آباد", value: 5000 },
      { name: "کلاردشت", value: 4000 },
      { name: "سوادکوه", value: 3000 },
      { name: "گلوگاه", value: 2000 },
      { name: "کیاسر", value: 1500 },
      { name: "سرخرود", value: 1000 },
      { name: "چالوس", value: 800 },
      { name: "نوشهر", value: 600 },
      { name: "رامسر", value: 400 },
      { name: "نکا", value: 300 },
      { name: "فریدونکنار", value: 200 },
      { name: "عباس‌آباد", value: 150 },
      { name: "کلاردشت", value: 100 },
      { name: "سوادکوه", value: 80 },
      { name: "گلوگاه", value: 60 },
      { name: "کیاسر", value: 40 },
      { name: "سرخرود", value: 30 },
      { name: "چالوس", value: 20 },
      { name: "نوشهر", value: 15 },
      { name: "رامسر", value: 10 },
      { name: "نکا", value: 8 },
      { name: "فریدونکنار", value: 6 },
      { name: "عباس‌آباد", value: 4 },
      { name: "کلاردشت", value: 3 },
      { name: "سوادکوه", value: 2 },
      { name: "گلوگاه", value: 1 },
    ],
  },
  {
    name: "کرمان",
    value: 3160000,
    counties: [
      { name: "کرمان", value: 800000 },
      { name: "رفسنجان", value: 200000 },
      { name: "جیرفت", value: 150000 },
      { name: "بم", value: 120000 },
      { name: "سیرجان", value: 100000 },
      { name: "شهربابک", value: 80000 },
      { name: "بردسیر", value: 60000 },
      { name: "رودبار جنوب", value: 50000 },
      { name: "عنبرآباد", value: 40000 },
      { name: "ریگان", value: 30000 },
      { name: "فهرج", value: 25000 },
      { name: "قلعه گنج", value: 20000 },
      { name: "فاریاب", value: 15000 },
      { name: "رودبار جنوب", value: 12000 },
      { name: "عنبرآباد", value: 10000 },
      { name: "ریگان", value: 8000 },
      { name: "فهرج", value: 6000 },
      { name: "قلعه گنج", value: 5000 },
      { name: "فاریاب", value: 4000 },
      { name: "رودبار جنوب", value: 3000 },
      { name: "عنبرآباد", value: 2000 },
      { name: "ریگان", value: 1500 },
      { name: "فهرج", value: 1000 },
      { name: "قلعه گنج", value: 800 },
      { name: "فاریاب", value: 600 },
      { name: "رودبار جنوب", value: 400 },
      { name: "عنبرآباد", value: 300 },
      { name: "ریگان", value: 200 },
      { name: "فهرج", value: 150 },
      { name: "قلعه گنج", value: 100 },
      { name: "فاریاب", value: 80 },
      { name: "رودبار جنوب", value: 60 },
      { name: "عنبرآباد", value: 40 },
      { name: "ریگان", value: 30 },
      { name: "فهرج", value: 20 },
      { name: "قلعه گنج", value: 15 },
      { name: "فاریاب", value: 10 },
      { name: "رودبار جنوب", value: 8 },
      { name: "عنبرآباد", value: 6 },
      { name: "ریگان", value: 4 },
      { name: "فهرج", value: 3 },
      { name: "قلعه گنج", value: 2 },
      { name: "فاریاب", value: 1 },
    ],
  },
  {
    name: "آذربایجان غربی",
    value: 3200000,
    counties: [
      { name: "ارومیه", value: 1000000 },
      { name: "خوی", value: 200000 },
      { name: "مرند", value: 150000 },
      { name: "مهاباد", value: 120000 },
      { name: "بوکان", value: 100000 },
      { name: "سلماس", value: 80000 },
      { name: "نقده", value: 60000 },
      { name: "میاندوآب", value: 50000 },
      { name: "شاهین‌دژ", value: 40000 },
      { name: "تکاب", value: 30000 },
      { name: "چالدران", value: 25000 },
      { name: "پیرانشهر", value: 20000 },
      { name: "سردشت", value: 15000 },
      { name: "بانه", value: 12000 },
      { name: "سقز", value: 10000 },
      { name: "مریوان", value: 8000 },
      { name: "قروه", value: 6000 },
      { name: "کامیاران", value: 5000 },
      { name: "سنندج", value: 4000 },
      { name: "دیواندره", value: 3000 },
      { name: "بیجار", value: 2000 },
      { name: "قروه", value: 1500 },
      { name: "کامیاران", value: 1000 },
      { name: "سنندج", value: 800 },
      { name: "دیواندره", value: 600 },
      { name: "بیجار", value: 400 },
      { name: "قروه", value: 300 },
      { name: "کامیاران", value: 200 },
      { name: "سنندج", value: 150 },
      { name: "دیواندره", value: 100 },
      { name: "بیجار", value: 80 },
      { name: "قروه", value: 60 },
      { name: "کامیاران", value: 40 },
      { name: "سنندج", value: 30 },
      { name: "دیواندره", value: 20 },
      { name: "بیجار", value: 15 },
      { name: "قروه", value: 10 },
      { name: "کامیاران", value: 8 },
      { name: "سنندج", value: 6 },
      { name: "دیواندره", value: 4 },
      { name: "بیجار", value: 3 },
      { name: "قروه", value: 2 },
      { name: "کامیاران", value: 1 },
    ],
  },
  {
    name: "لرستان",
    value: 1760000,
    counties: [
      { name: "خرم‌آباد", value: 500000 },
      { name: "بروجرد", value: 300000 },
      { name: "دورود", value: 200000 },
      { name: "کوهدشت", value: 150000 },
      { name: "الیگودرز", value: 120000 },
      { name: "نورآباد", value: 100000 },
      { name: "ازنا", value: 80000 },
      { name: "سلسله", value: 60000 },
      { name: "دلفان", value: 50000 },
      { name: "رومشکان", value: 40000 },
      { name: "پل‌دختر", value: 30000 },
      { name: "کوهدشت", value: 25000 },
      { name: "الیگودرز", value: 20000 },
      { name: "نورآباد", value: 15000 },
      { name: "ازنا", value: 12000 },
      { name: "سلسله", value: 10000 },
      { name: "دلفان", value: 8000 },
      { name: "رومشکان", value: 6000 },
      { name: "پل‌دختر", value: 5000 },
      { name: "کوهدشت", value: 4000 },
      { name: "الیگودرز", value: 3000 },
      { name: "نورآباد", value: 2000 },
      { name: "ازنا", value: 1500 },
      { name: "سلسله", value: 1000 },
      { name: "دلفان", value: 800 },
      { name: "رومشکان", value: 600 },
      { name: "پل‌دختر", value: 400 },
      { name: "کوهدشت", value: 300 },
      { name: "الیگودرز", value: 200 },
      { name: "نورآباد", value: 150 },
      { name: "ازنا", value: 100 },
      { name: "سلسله", value: 80 },
      { name: "دلفان", value: 60 },
      { name: "رومشکان", value: 40 },
      { name: "پل‌دختر", value: 30 },
      { name: "کوهدشت", value: 20 },
      { name: "الیگودرز", value: 15 },
      { name: "نورآباد", value: 10 },
      { name: "ازنا", value: 8 },
      { name: "سلسله", value: 6 },
      { name: "دلفان", value: 4 },
      { name: "رومشکان", value: 3 },
      { name: "پل‌دختر", value: 2 },
      { name: "کوهدشت", value: 1 },
    ],
  },
  {
    name: "کردستان",
    value: 1600000,
    counties: [
      { name: "سنندج", value: 500000 },
      { name: "مریوان", value: 200000 },
      { name: "سقز", value: 150000 },
      { name: "قروه", value: 120000 },
      { name: "کامیاران", value: 100000 },
      { name: "بیجار", value: 80000 },
      { name: "دیواندره", value: 60000 },
      { name: "سروآباد", value: 50000 },
      { name: "بانه", value: 40000 },
      { name: "سردشت", value: 30000 },
      { name: "پیرانشهر", value: 25000 },
      { name: "چالدران", value: 20000 },
      { name: "تکاب", value: 15000 },
      { name: "شاهین‌دژ", value: 12000 },
      { name: "میاندوآب", value: 10000 },
      { name: "نقده", value: 8000 },
      { name: "سلماس", value: 6000 },
      { name: "بوکان", value: 5000 },
      { name: "مهاباد", value: 4000 },
      { name: "مرند", value: 3000 },
      { name: "خوی", value: 2000 },
      { name: "ارومیه", value: 1500 },
      { name: "سلماس", value: 1000 },
      { name: "بوکان", value: 800 },
      { name: "مهاباد", value: 600 },
      { name: "مرند", value: 400 },
      { name: "خوی", value: 300 },
      { name: "ارومیه", value: 200 },
      { name: "سلماس", value: 150 },
      { name: "بوکان", value: 100 },
      { name: "مهاباد", value: 80 },
      { name: "مرند", value: 60 },
      { name: "خوی", value: 40 },
      { name: "ارومیه", value: 30 },
      { name: "سلماس", value: 20 },
      { name: "بوکان", value: 15 },
      { name: "مهاباد", value: 10 },
      { name: "مرند", value: 8 },
      { name: "خوی", value: 6 },
      { name: "ارومیه", value: 4 },
      { name: "سلماس", value: 3 },
      { name: "بوکان", value: 2 },
      { name: "مهاباد", value: 1 },
    ],
  },
  {
    name: "همدان",
    value: 1730000,
    counties: [
      { name: "همدان", value: 600000 },
      { name: "ملایر", value: 200000 },
      { name: "نهاوند", value: 150000 },
      { name: "کبودراهنگ", value: 120000 },
      { name: "بهار", value: 100000 },
      { name: "رزن", value: 80000 },
      { name: "فامنین", value: 60000 },
      { name: "اسدآباد", value: 50000 },
      { name: "تویسرکان", value: 40000 },
      { name: "بهار", value: 30000 },
      { name: "رزن", value: 25000 },
      { name: "فامنین", value: 20000 },
      { name: "اسدآباد", value: 15000 },
      { name: "تویسرکان", value: 12000 },
      { name: "بهار", value: 10000 },
      { name: "رزن", value: 8000 },
      { name: "فامنین", value: 6000 },
      { name: "اسدآباد", value: 5000 },
      { name: "تویسرکان", value: 4000 },
      { name: "بهار", value: 3000 },
      { name: "رزن", value: 2000 },
      { name: "فامنین", value: 1500 },
      { name: "اسدآباد", value: 1000 },
      { name: "تویسرکان", value: 800 },
      { name: "بهار", value: 600 },
      { name: "رزن", value: 400 },
      { name: "فامنین", value: 300 },
      { name: "اسدآباد", value: 200 },
      { name: "تویسرکان", value: 150 },
      { name: "بهار", value: 100 },
      { name: "رزن", value: 80 },
      { name: "فامنین", value: 60 },
      { name: "اسدآباد", value: 40 },
      { name: "تویسرکان", value: 30 },
      { name: "بهار", value: 20 },
      { name: "رزن", value: 15 },
      { name: "فامنین", value: 10 },
      { name: "اسدآباد", value: 8 },
      { name: "تویسرکان", value: 6 },
      { name: "بهار", value: 4 },
      { name: "رزن", value: 3 },
      { name: "فامنین", value: 2 },
      { name: "اسدآباد", value: 1 },
    ],
  },
  {
    name: "یزد",
    value: 1130000,
    counties: [
      { name: "یزد", value: 500000 },
      { name: "میبد", value: 100000 },
      { name: "اردکان", value: 80000 },
      { name: "بافق", value: 60000 },
      { name: "تفت", value: 50000 },
      { name: "ابرکوه", value: 40000 },
      { name: "هرات", value: 30000 },
      { name: "بهاباد", value: 25000 },
      { name: "خاتم", value: 20000 },
      { name: "مهریز", value: 15000 },
      { name: "اشکذر", value: 12000 },
      { name: "بهاباد", value: 10000 },
      { name: "خاتم", value: 8000 },
      { name: "مهریز", value: 6000 },
      { name: "اشکذر", value: 5000 },
      { name: "بهاباد", value: 4000 },
      { name: "خاتم", value: 3000 },
      { name: "مهریز", value: 2000 },
      { name: "اشکذر", value: 1500 },
      { name: "بهاباد", value: 1000 },
      { name: "خاتم", value: 800 },
      { name: "مهریز", value: 600 },
      { name: "اشکذر", value: 400 },
      { name: "بهاباد", value: 300 },
      { name: "خاتم", value: 200 },
      { name: "مهریز", value: 150 },
      { name: "اشکذر", value: 100 },
      { name: "بهاباد", value: 80 },
      { name: "خاتم", value: 60 },
      { name: "مهریز", value: 40 },
      { name: "اشکذر", value: 30 },
      { name: "بهاباد", value: 20 },
      { name: "خاتم", value: 15 },
      { name: "مهریز", value: 10 },
      { name: "اشکذر", value: 8 },
      { name: "بهاباد", value: 6 },
      { name: "خاتم", value: 4 },
      { name: "مهریز", value: 3 },
      { name: "اشکذر", value: 2 },
      { name: "بهاباد", value: 1 },
    ],
  },
  {
    name: "زنجان",
    value: 1050000,
    counties: [
      { name: "زنجان", value: 500000 },
      { name: "ابهر", value: 150000 },
      { name: "خدابنده", value: 100000 },
      { name: "ماهنشان", value: 80000 },
      { name: "ایجرود", value: 60000 },
      { name: "خرمدره", value: 50000 },
      { name: "سلطانیه", value: 40000 },
      { name: "طارم", value: 30000 },
      { name: "خدابنده", value: 25000 },
      { name: "ماهنشان", value: 20000 },
      { name: "ایجرود", value: 15000 },
      { name: "خرمدره", value: 12000 },
      { name: "سلطانیه", value: 10000 },
      { name: "طارم", value: 8000 },
      { name: "خدابنده", value: 6000 },
      { name: "ماهنشان", value: 5000 },
      { name: "ایجرود", value: 4000 },
      { name: "خرمدره", value: 3000 },
      { name: "سلطانیه", value: 2000 },
      { name: "طارم", value: 1500 },
      { name: "خدابنده", value: 1000 },
      { name: "ماهنشان", value: 800 },
      { name: "ایجرود", value: 600 },
      { name: "خرمدره", value: 400 },
      { name: "سلطانیه", value: 300 },
      { name: "طارم", value: 200 },
      { name: "خدابنده", value: 150 },
      { name: "ماهنشان", value: 100 },
      { name: "ایجرود", value: 80 },
      { name: "خرمدره", value: 60 },
      { name: "سلطانیه", value: 40 },
      { name: "طارم", value: 30 },
      { name: "خدابنده", value: 20 },
      { name: "ماهنشان", value: 15 },
      { name: "ایجرود", value: 10 },
      { name: "خرمدره", value: 8 },
      { name: "سلطانیه", value: 6 },
      { name: "طارم", value: 4 },
      { name: "خدابنده", value: 3 },
      { name: "ماهنشان", value: 2 },
      { name: "ایجرود", value: 1 },
    ],
  },
  {
    name: "مرکزی",
    value: 1420000,
    counties: [
      { name: "اراک", value: 600000 },
      { name: "ساوه", value: 200000 },
      { name: "محلات", value: 150000 },
      { name: "خمین", value: 120000 },
      { name: "دلیجان", value: 100000 },
      { name: "تفرش", value: 80000 },
      { name: "کمیجان", value: 60000 },
      { name: "آشتیان", value: 50000 },
      { name: "شازند", value: 40000 },
      { name: "زرندیه", value: 30000 },
      { name: "فراهان", value: 25000 },
      { name: "کمیجان", value: 20000 },
      { name: "آشتیان", value: 15000 },
      { name: "شازند", value: 12000 },
      { name: "زرندیه", value: 10000 },
      { name: "فراهان", value: 8000 },
      { name: "کمیجان", value: 6000 },
      { name: "آشتیان", value: 5000 },
      { name: "شازند", value: 4000 },
      { name: "زرندیه", value: 3000 },
      { name: "فراهان", value: 2000 },
      { name: "کمیجان", value: 1500 },
      { name: "آشتیان", value: 1000 },
      { name: "شازند", value: 800 },
      { name: "زرندیه", value: 600 },
      { name: "فراهان", value: 400 },
      { name: "کمیجان", value: 300 },
      { name: "آشتیان", value: 200 },
      { name: "شازند", value: 150 },
      { name: "زرندیه", value: 100 },
      { name: "فراهان", value: 80 },
      { name: "کمیجان", value: 60 },
      { name: "آشتیان", value: 40 },
      { name: "شازند", value: 30 },
      { name: "زرندیه", value: 20 },
      { name: "فراهان", value: 15 },
      { name: "کمیجان", value: 10 },
      { name: "آشتیان", value: 8 },
      { name: "شازند", value: 6 },
      { name: "زرندیه", value: 4 },
      { name: "فراهان", value: 3 },
      { name: "کمیجان", value: 2 },
      { name: "آشتیان", value: 1 },
    ],
  },
  {
    name: "هرمزگان",
    value: 1770000,
    counties: [
      { name: "بندرعباس", value: 600000 },
      { name: "میناب", value: 200000 },
      { name: "قشم", value: 150000 },
      { name: "کیش", value: 100000 },
      { name: "بندر لنگه", value: 80000 },
      { name: "جاسک", value: 60000 },
      { name: "رودان", value: 50000 },
      { name: "حاجی‌آباد", value: 40000 },
      { name: "پارسیان", value: 30000 },
      { name: "بستک", value: 25000 },
      { name: "خمیر", value: 20000 },
      { name: "سیریک", value: 15000 },
      { name: "رودان", value: 12000 },
      { name: "حاجی‌آباد", value: 10000 },
      { name: "پارسیان", value: 8000 },
      { name: "بستک", value: 6000 },
      { name: "خمیر", value: 5000 },
      { name: "سیریک", value: 4000 },
      { name: "رودان", value: 3000 },
      { name: "حاجی‌آباد", value: 2000 },
      { name: "پارسیان", value: 1500 },
      { name: "بستک", value: 1000 },
      { name: "خمیر", value: 800 },
      { name: "سیریک", value: 600 },
      { name: "رودان", value: 400 },
      { name: "حاجی‌آباد", value: 300 },
      { name: "پارسیان", value: 200 },
      { name: "بستک", value: 150 },
      { name: "خمیر", value: 100 },
      { name: "سیریک", value: 80 },
      { name: "رودان", value: 60 },
      { name: "حاجی‌آباد", value: 40 },
      { name: "پارسیان", value: 30 },
      { name: "بستک", value: 20 },
      { name: "خمیر", value: 15 },
      { name: "سیریک", value: 10 },
      { name: "رودان", value: 8 },
      { name: "حاجی‌آباد", value: 6 },
      { name: "پارسیان", value: 4 },
      { name: "بستک", value: 3 },
      { name: "خمیر", value: 2 },
      { name: "سیریک", value: 1 },
    ],
  },
  {
    name: "سیستان و بلوچستان",
    value: 2770000,
    counties: [
      { name: "زاهدان", value: 800000 },
      { name: "زابل", value: 200000 },
      { name: "چابهار", value: 150000 },
      { name: "ایرانشهر", value: 120000 },
      { name: "خاش", value: 100000 },
      { name: "سراوان", value: 80000 },
      { name: "نیک‌شهر", value: 60000 },
      { name: "کنارک", value: 50000 },
      { name: "دلگان", value: 40000 },
      { name: "فنوج", value: 30000 },
      { name: "قصرقند", value: 25000 },
      { name: "میرجاوه", value: 20000 },
      { name: "سیب و سوران", value: 15000 },
      { name: "راسک", value: 12000 },
      { name: "سرباز", value: 10000 },
      { name: "کنارک", value: 8000 },
      { name: "دلگان", value: 6000 },
      { name: "فنوج", value: 5000 },
      { name: "قصرقند", value: 4000 },
      { name: "میرجاوه", value: 3000 },
      { name: "سیب و سوران", value: 2000 },
      { name: "راسک", value: 1500 },
      { name: "سرباز", value: 1000 },
      { name: "کنارک", value: 800 },
      { name: "دلگان", value: 600 },
      { name: "فنوج", value: 400 },
      { name: "قصرقند", value: 300 },
      { name: "میرجاوه", value: 200 },
      { name: "سیب و سوران", value: 150 },
      { name: "راسک", value: 100 },
      { name: "سرباز", value: 80 },
      { name: "کنارک", value: 60 },
      { name: "دلگان", value: 40 },
      { name: "فنوج", value: 30 },
      { name: "قصرقند", value: 20 },
      { name: "میرجاوه", value: 15 },
      { name: "سیب و سوران", value: 10 },
      { name: "راسک", value: 8 },
      { name: "سرباز", value: 6 },
      { name: "کنارک", value: 4 },
      { name: "دلگان", value: 3 },
      { name: "فنوج", value: 2 },
      { name: "قصرقند", value: 1 },
    ],
  },
  {
    name: "گلستان",
    value: 1860000,
    counties: [
      { name: "گرگان", value: 400000 },
      { name: "آق‌قلا", value: 150000 },
      { name: "گنبد کاووس", value: 120000 },
      { name: "مینودشت", value: 100000 },
      { name: "کردکوی", value: 80000 },
      { name: "بندر گز", value: 60000 },
      { name: "ترکمن", value: 50000 },
      { name: "کلاله", value: 40000 },
      { name: "مراوه‌تپه", value: 30000 },
      { name: "فاضل‌آباد", value: 25000 },
      { name: "رامیان", value: 20000 },
      { name: "علی‌آباد کتول", value: 15000 },
      { name: "فاضل‌آباد", value: 12000 },
      { name: "رامیان", value: 10000 },
      { name: "علی‌آباد کتول", value: 8000 },
      { name: "فاضل‌آباد", value: 6000 },
      { name: "رامیان", value: 5000 },
      { name: "علی‌آباد کتول", value: 4000 },
      { name: "فاضل‌آباد", value: 3000 },
      { name: "رامیان", value: 2000 },
      { name: "علی‌آباد کتول", value: 1500 },
      { name: "فاضل‌آباد", value: 1000 },
      { name: "رامیان", value: 800 },
      { name: "علی‌آباد کتول", value: 600 },
      { name: "فاضل‌آباد", value: 400 },
      { name: "رامیان", value: 300 },
      { name: "علی‌آباد کتول", value: 200 },
      { name: "فاضل‌آباد", value: 150 },
      { name: "رامیان", value: 100 },
      { name: "علی‌آباد کتول", value: 80 },
      { name: "فاضل‌آباد", value: 60 },
      { name: "رامیان", value: 40 },
      { name: "علی‌آباد کتول", value: 30 },
      { name: "فاضل‌آباد", value: 20 },
      { name: "رامیان", value: 15 },
      { name: "علی‌آباد کتول", value: 10 },
      { name: "فاضل‌آباد", value: 8 },
      { name: "رامیان", value: 6 },
      { name: "علی‌آباد کتول", value: 4 },
      { name: "فاضل‌آباد", value: 3 },
      { name: "رامیان", value: 2 },
      { name: "علی‌آباد کتول", value: 1 },
    ],
  },
  {
    name: "قزوین",
    value: 1270000,
    counties: [
      { name: "قزوین", value: 500000 },
      { name: "تاکستان", value: 150000 },
      { name: "آبیک", value: 120000 },
      { name: "بوئین‌زهرا", value: 100000 },
      { name: "الوند", value: 80000 },
      { name: "آوج", value: 60000 },
      { name: "محمودآباد", value: 50000 },
      { name: "تاکستان", value: 40000 },
      { name: "آبیک", value: 30000 },
      { name: "بوئین‌زهرا", value: 25000 },
      { name: "الوند", value: 20000 },
      { name: "آوج", value: 15000 },
      { name: "محمودآباد", value: 12000 },
      { name: "تاکستان", value: 10000 },
      { name: "آبیک", value: 8000 },
      { name: "بوئین‌زهرا", value: 6000 },
      { name: "الوند", value: 5000 },
      { name: "آوج", value: 4000 },
      { name: "محمودآباد", value: 3000 },
      { name: "تاکستان", value: 2000 },
      { name: "آبیک", value: 1500 },
      { name: "بوئین‌زهرا", value: 1000 },
      { name: "الوند", value: 800 },
      { name: "آوج", value: 600 },
      { name: "محمودآباد", value: 400 },
      { name: "تاکستان", value: 300 },
      { name: "آبیک", value: 200 },
      { name: "بوئین‌زهرا", value: 150 },
      { name: "الوند", value: 100 },
      { name: "آوج", value: 80 },
      { name: "محمودآباد", value: 60 },
      { name: "تاکستان", value: 40 },
      { name: "آبیک", value: 30 },
      { name: "بوئین‌زهرا", value: 20 },
      { name: "الوند", value: 15 },
      { name: "آوج", value: 10 },
      { name: "محمودآباد", value: 8 },
      { name: "تاکستان", value: 6 },
      { name: "آبیک", value: 4 },
      { name: "بوئین‌زهرا", value: 3 },
      { name: "الوند", value: 2 },
      { name: "آوج", value: 1 },
    ],
  },
  {
    name: "قم",
    value: 1290000,
    counties: [
      { name: "قم", value: 1200000 },
      { name: "کهک", value: 50000 },
      { name: "سلفچگان", value: 30000 },
      { name: "کهک", value: 20000 },
      { name: "سلفچگان", value: 15000 },
      { name: "کهک", value: 10000 },
      { name: "سلفچگان", value: 8000 },
      { name: "کهک", value: 6000 },
      { name: "سلفچگان", value: 4000 },
      { name: "کهک", value: 3000 },
      { name: "سلفچگان", value: 2000 },
      { name: "کهک", value: 1500 },
      { name: "سلفچگان", value: 1000 },
      { name: "کهک", value: 800 },
      { name: "سلفچگان", value: 600 },
      { name: "کهک", value: 400 },
      { name: "سلفچگان", value: 300 },
      { name: "کهک", value: 200 },
      { name: "سلفچگان", value: 150 },
      { name: "کهک", value: 100 },
      { name: "سلفچگان", value: 80 },
      { name: "کهک", value: 60 },
      { name: "سلفچگان", value: 40 },
      { name: "کهک", value: 30 },
      { name: "سلفچگان", value: 20 },
      { name: "کهک", value: 15 },
      { name: "سلفچگان", value: 10 },
      { name: "کهک", value: 8 },
      { name: "سلفچگان", value: 6 },
      { name: "کهک", value: 4 },
      { name: "سلفچگان", value: 3 },
      { name: "کهک", value: 2 },
      { name: "سلفچگان", value: 1 },
    ],
  },
  {
    name: "سمنان",
    value: 702000,
    counties: [
      { name: "سمنان", value: 300000 },
      { name: "شاهرود", value: 200000 },
      { name: "دامغان", value: 100000 },
      { name: "گرمسار", value: 80000 },
      { name: "مهدیشهر", value: 60000 },
      { name: "بسطام", value: 40000 },
      { name: "میامی", value: 30000 },
      { name: "آرادان", value: 20000 },
      { name: "بسطام", value: 15000 },
      { name: "میامی", value: 12000 },
      { name: "آرادان", value: 10000 },
      { name: "بسطام", value: 8000 },
      { name: "میامی", value: 6000 },
      { name: "آرادان", value: 5000 },
      { name: "بسطام", value: 4000 },
      { name: "میامی", value: 3000 },
      { name: "آرادان", value: 2000 },
      { name: "بسطام", value: 1500 },
      { name: "میامی", value: 1000 },
      { name: "آرادان", value: 800 },
      { name: "بسطام", value: 600 },
      { name: "میامی", value: 400 },
      { name: "آرادان", value: 300 },
      { name: "بسطام", value: 200 },
      { name: "میامی", value: 150 },
      { name: "آرادان", value: 100 },
      { name: "بسطام", value: 80 },
      { name: "میامی", value: 60 },
      { name: "آرادان", value: 40 },
      { name: "بسطام", value: 30 },
      { name: "میامی", value: 20 },
      { name: "آرادان", value: 15 },
      { name: "بسطام", value: 10 },
      { name: "میامی", value: 8 },
      { name: "آرادان", value: 6 },
      { name: "بسطام", value: 4 },
      { name: "میامی", value: 3 },
      { name: "آرادان", value: 2 },
      { name: "بسطام", value: 1 },
    ],
  },
  {
    name: "کهگیلویه و بویراحمد",
    value: 713000,
    counties: [
      { name: "یاسوج", value: 200000 },
      { name: "دوگنبدان", value: 100000 },
      { name: "سی‌سخت", value: 80000 },
      { name: "مارگون", value: 60000 },
      { name: "بویراحمد", value: 50000 },
      { name: "دنا", value: 40000 },
      { name: "چرام", value: 30000 },
      { name: "لنده", value: 25000 },
      { name: "بهمئی", value: 20000 },
      { name: "مارگون", value: 15000 },
      { name: "بویراحمد", value: 12000 },
      { name: "دنا", value: 10000 },
      { name: "چرام", value: 8000 },
      { name: "لنده", value: 6000 },
      { name: "بهمئی", value: 5000 },
      { name: "مارگون", value: 4000 },
      { name: "بویراحمد", value: 3000 },
      { name: "دنا", value: 2000 },
      { name: "چرام", value: 1500 },
      { name: "لنده", value: 1000 },
      { name: "بهمئی", value: 800 },
      { name: "مارگون", value: 600 },
      { name: "بویراحمد", value: 400 },
      { name: "دنا", value: 300 },
      { name: "چرام", value: 200 },
      { name: "لنده", value: 150 },
      { name: "بهمئی", value: 100 },
      { name: "مارگون", value: 80 },
      { name: "بویراحمد", value: 60 },
      { name: "دنا", value: 40 },
      { name: "چرام", value: 30 },
      { name: "لنده", value: 20 },
      { name: "بهمئی", value: 15 },
      { name: "مارگون", value: 10 },
      { name: "بویراحمد", value: 8 },
      { name: "دنا", value: 6 },
      { name: "چرام", value: 4 },
      { name: "لنده", value: 3 },
      { name: "بهمئی", value: 2 },
      { name: "مارگون", value: 1 },
    ],
  },
  {
    name: "کرمانشاه",
    value: 1950000,
    counties: [
      { name: "کرمانشاه", value: 1000000 },
      { name: "اسلام‌آباد غرب", value: 200000 },
      { name: "کنگاور", value: 150000 },
      { name: "هرسین", value: 120000 },
      { name: "صحنه", value: 100000 },
      { name: "سنقر", value: 80000 },
      { name: "قصرشیرین", value: 60000 },
      { name: "گیلان غرب", value: 50000 },
      { name: "سرپل ذهاب", value: 40000 },
      { name: "ثلاث باباجانی", value: 30000 },
      { name: "جوانرود", value: 25000 },
      { name: "دالاهو", value: 20000 },
      { name: "سنقر", value: 15000 },
      { name: "قصرشیرین", value: 12000 },
      { name: "گیلان غرب", value: 10000 },
      { name: "سرپل ذهاب", value: 8000 },
      { name: "ثلاث باباجانی", value: 6000 },
      { name: "جوانرود", value: 5000 },
      { name: "دالاهو", value: 4000 },
      { name: "سنقر", value: 3000 },
      { name: "قصرشیرین", value: 2000 },
      { name: "گیلان غرب", value: 1500 },
      { name: "سرپل ذهاب", value: 1000 },
      { name: "ثلاث باباجانی", value: 800 },
      { name: "جوانرود", value: 600 },
      { name: "دالاهو", value: 400 },
      { name: "سنقر", value: 300 },
      { name: "قصرشیرین", value: 200 },
      { name: "گیلان غرب", value: 150 },
      { name: "سرپل ذهاب", value: 100 },
      { name: "ثلاث باباجانی", value: 80 },
      { name: "جوانرود", value: 60 },
      { name: "دالاهو", value: 40 },
      { name: "سنقر", value: 30 },
      { name: "قصرشیرین", value: 20 },
      { name: "گیلان غرب", value: 15 },
      { name: "سرپل ذهاب", value: 10 },
      { name: "ثلاث باباجانی", value: 8 },
      { name: "جوانرود", value: 6 },
      { name: "دالاهو", value: 4 },
      { name: "سنقر", value: 3 },
      { name: "قصرشیرین", value: 2 },
      { name: "گیلان غرب", value: 1 },
    ],
  },
  {
    name: "ایلام",
    value: 580000,
    counties: [
      { name: "ایلام", value: 200000 },
      { name: "دهلران", value: 100000 },
      { name: "آبدانان", value: 80000 },
      { name: "دره‌شهر", value: 60000 },
      { name: "مهران", value: 50000 },
      { name: "سرابله", value: 40000 },
      { name: "چرداول", value: 30000 },
      { name: "بدره", value: 25000 },
      { name: "ملکشاهی", value: 20000 },
      { name: "سرابله", value: 15000 },
      { name: "چرداول", value: 12000 },
      { name: "بدره", value: 10000 },
      { name: "ملکشاهی", value: 8000 },
      { name: "سرابله", value: 6000 },
      { name: "چرداول", value: 5000 },
      { name: "بدره", value: 4000 },
      { name: "ملکشاهی", value: 3000 },
      { name: "سرابله", value: 2000 },
      { name: "چرداول", value: 1500 },
      { name: "بدره", value: 1000 },
      { name: "ملکشاهی", value: 800 },
      { name: "سرابله", value: 600 },
      { name: "چرداول", value: 400 },
      { name: "بدره", value: 300 },
      { name: "ملکشاهی", value: 200 },
      { name: "سرابله", value: 150 },
      { name: "چرداول", value: 100 },
      { name: "بدره", value: 80 },
      { name: "ملکشاهی", value: 60 },
      { name: "سرابله", value: 40 },
      { name: "چرداول", value: 30 },
      { name: "بدره", value: 20 },
      { name: "ملکشاهی", value: 15 },
      { name: "سرابله", value: 10 },
      { name: "چرداول", value: 8 },
      { name: "بدره", value: 6 },
      { name: "ملکشاهی", value: 4 },
      { name: "سرابله", value: 3 },
      { name: "چرداول", value: 2 },
      { name: "بدره", value: 1 },
    ],
  },
  {
    name: "بوشهر",
    value: 1160000,
    counties: [
      { name: "بوشهر", value: 300000 },
      { name: "برازجان", value: 150000 },
      { name: "گناوه", value: 120000 },
      { name: "کنگان", value: 100000 },
      { name: "دشتستان", value: 80000 },
      { name: "تنگستان", value: 60000 },
      { name: "جم", value: 50000 },
      { name: "دیر", value: 40000 },
      { name: "عسلویه", value: 30000 },
      { name: "کنگان", value: 25000 },
      { name: "دشتستان", value: 20000 },
      { name: "تنگستان", value: 15000 },
      { name: "جم", value: 12000 },
      { name: "دیر", value: 10000 },
      { name: "عسلویه", value: 8000 },
      { name: "کنگان", value: 6000 },
      { name: "دشتستان", value: 5000 },
      { name: "تنگستان", value: 4000 },
      { name: "جم", value: 3000 },
      { name: "دیر", value: 2000 },
      { name: "عسلویه", value: 1500 },
      { name: "کنگان", value: 1000 },
      { name: "دشتستان", value: 800 },
      { name: "تنگستان", value: 600 },
      { name: "جم", value: 400 },
      { name: "دیر", value: 300 },
      { name: "عسلویه", value: 200 },
      { name: "کنگان", value: 150 },
      { name: "دشتستان", value: 100 },
      { name: "تنگستان", value: 80 },
      { name: "جم", value: 60 },
      { name: "دیر", value: 40 },
      { name: "عسلویه", value: 30 },
      { name: "کنگان", value: 20 },
      { name: "دشتستان", value: 15 },
      { name: "تنگستان", value: 10 },
      { name: "جم", value: 8 },
      { name: "دیر", value: 6 },
      { name: "عسلویه", value: 4 },
      { name: "کنگان", value: 3 },
      { name: "دشتستان", value: 2 },
      { name: "تنگستان", value: 1 },
    ],
  },
  {
    name: "چهارمحال و بختیاری",
    value: 947000,
    counties: [
      { name: "شهرکرد", value: 300000 },
      { name: "بروجن", value: 150000 },
      { name: "لردگان", value: 120000 },
      { name: "اردل", value: 100000 },
      { name: "فارسان", value: 80000 },
      { name: "کوهرنگ", value: 60000 },
      { name: "کیان", value: 50000 },
      { name: "بن", value: 40000 },
      { name: "سامان", value: 30000 },
      { name: "کوهرنگ", value: 25000 },
      { name: "کیان", value: 20000 },
      { name: "بن", value: 15000 },
      { name: "سامان", value: 12000 },
      { name: "کوهرنگ", value: 10000 },
      { name: "کیان", value: 8000 },
      { name: "بن", value: 6000 },
      { name: "سامان", value: 5000 },
      { name: "کوهرنگ", value: 4000 },
      { name: "کیان", value: 3000 },
      { name: "بن", value: 2000 },
      { name: "سامان", value: 1500 },
      { name: "کوهرنگ", value: 1000 },
      { name: "کیان", value: 800 },
      { name: "بن", value: 600 },
      { name: "سامان", value: 400 },
      { name: "کوهرنگ", value: 300 },
      { name: "کیان", value: 200 },
      { name: "بن", value: 150 },
      { name: "سامان", value: 100 },
      { name: "کوهرنگ", value: 80 },
      { name: "کیان", value: 60 },
      { name: "بن", value: 40 },
      { name: "سامان", value: 30 },
      { name: "کوهرنگ", value: 20 },
      { name: "کیان", value: 15 },
      { name: "بن", value: 10 },
      { name: "سامان", value: 8 },
      { name: "کوهرنگ", value: 6 },
      { name: "کیان", value: 4 },
      { name: "بن", value: 3 },
      { name: "سامان", value: 2 },
      { name: "کوهرنگ", value: 1 },
    ],
  },
  {
    name: "خراسان شمالی",
    value: 863000,
    counties: [
      { name: "بجنورد", value: 300000 },
      { name: "شیروان", value: 150000 },
      { name: "فاروج", value: 100000 },
      { name: "اسفراین", value: 80000 },
      { name: "مانه و سملقان", value: 60000 },
      { name: "رازوجرگلان", value: 50000 },
      { name: "جاجرم", value: 40000 },
      { name: "فاروج", value: 30000 },
      { name: "اسفراین", value: 25000 },
      { name: "مانه و سملقان", value: 20000 },
      { name: "رازوجرگلان", value: 15000 },
      { name: "جاجرم", value: 12000 },
      { name: "فاروج", value: 10000 },
      { name: "اسفراین", value: 8000 },
      { name: "مانه و سملقان", value: 6000 },
      { name: "رازوجرگلان", value: 5000 },
      { name: "جاجرم", value: 4000 },
      { name: "فاروج", value: 3000 },
      { name: "اسفراین", value: 2000 },
      { name: "مانه و سملقان", value: 1500 },
      { name: "رازوجرگلان", value: 1000 },
      { name: "جاجرم", value: 800 },
      { name: "فاروج", value: 600 },
      { name: "اسفراین", value: 400 },
      { name: "مانه و سملقان", value: 300 },
      { name: "رازوجرگلان", value: 200 },
      { name: "جاجرم", value: 150 },
      { name: "فاروج", value: 100 },
      { name: "اسفراین", value: 80 },
      { name: "مانه و سملقان", value: 60 },
      { name: "رازوجرگلان", value: 40 },
      { name: "جاجرم", value: 30 },
      { name: "فاروج", value: 20 },
      { name: "اسفراین", value: 15 },
      { name: "مانه و سملقان", value: 10 },
      { name: "رازوجرگلان", value: 8 },
      { name: "جاجرم", value: 6 },
      { name: "فاروج", value: 4 },
      { name: "اسفراین", value: 3 },
      { name: "مانه و سملقان", value: 2 },
      { name: "رازوجرگلان", value: 1 },
    ],
  },
  {
    name: "اردبیل",
    value: 1290000,
    counties: [
      { name: "اردبیل", value: 500000 },
      { name: "پارس‌آباد", value: 200000 },
      { name: "خلخال", value: 150000 },
      { name: "مشگین‌شهر", value: 120000 },
      { name: "گرمی", value: 100000 },
      { name: "بیله‌سوار", value: 80000 },
      { name: "کوثر", value: 60000 },
      { name: "سرعین", value: 50000 },
      { name: "نمین", value: 40000 },
      { name: "گرمی", value: 30000 },
      { name: "بیله‌سوار", value: 25000 },
      { name: "کوثر", value: 20000 },
      { name: "سرعین", value: 15000 },
      { name: "نمین", value: 12000 },
      { name: "گرمی", value: 10000 },
      { name: "بیله‌سوار", value: 8000 },
      { name: "کوثر", value: 6000 },
      { name: "سرعین", value: 5000 },
      { name: "نمین", value: 4000 },
      { name: "گرمی", value: 3000 },
      { name: "بیله‌سوار", value: 2000 },
      { name: "کوثر", value: 1500 },
      { name: "سرعین", value: 1000 },
      { name: "نمین", value: 800 },
      { name: "گرمی", value: 600 },
      { name: "بیله‌سوار", value: 400 },
      { name: "کوثر", value: 300 },
      { name: "سرعین", value: 200 },
      { name: "نمین", value: 150 },
      { name: "گرمی", value: 100 },
      { name: "بیله‌سوار", value: 80 },
      { name: "کوثر", value: 60 },
      { name: "سرعین", value: 40 },
      { name: "نمین", value: 30 },
      { name: "گرمی", value: 20 },
      { name: "بیله‌سوار", value: 15 },
      { name: "کوثر", value: 10 },
      { name: "سرعین", value: 8 },
      { name: "نمین", value: 6 },
      { name: "گرمی", value: 4 },
      { name: "بیله‌سوار", value: 3 },
      { name: "کوثر", value: 2 },
      { name: "سرعین", value: 1 },
    ],
  },
  {
    name: "البرز",
    value: 2710000,
    counties: [
      { name: "کرج", value: 2000000 },
      { name: "نظرآباد", value: 200000 },
      { name: "ساوجبلاغ", value: 150000 },
      { name: "طالقان", value: 100000 },
      { name: "فردیس", value: 80000 },
      { name: "ماهدشت", value: 60000 },
      { name: "هشتگرد", value: 50000 },
      { name: "نظرآباد", value: 40000 },
      { name: "ساوجبلاغ", value: 30000 },
      { name: "طالقان", value: 25000 },
      { name: "فردیس", value: 20000 },
      { name: "ماهدشت", value: 15000 },
      { name: "هشتگرد", value: 12000 },
      { name: "نظرآباد", value: 10000 },
      { name: "ساوجبلاغ", value: 8000 },
      { name: "طالقان", value: 6000 },
      { name: "فردیس", value: 5000 },
      { name: "ماهدشت", value: 4000 },
      { name: "هشتگرد", value: 3000 },
      { name: "نظرآباد", value: 2000 },
      { name: "ساوجبلاغ", value: 1500 },
      { name: "طالقان", value: 1000 },
      { name: "فردیس", value: 800 },
      { name: "ماهدشت", value: 600 },
      { name: "هشتگرد", value: 400 },
      { name: "نظرآباد", value: 300 },
      { name: "ساوجبلاغ", value: 200 },
      { name: "طالقان", value: 150 },
      { name: "فردیس", value: 100 },
      { name: "ماهدشت", value: 80 },
      { name: "هشتگرد", value: 60 },
      { name: "نظرآباد", value: 40 },
      { name: "ساوجبلاغ", value: 30 },
      { name: "طالقان", value: 20 },
      { name: "فردیس", value: 15 },
      { name: "ماهدشت", value: 10 },
      { name: "هشتگرد", value: 8 },
      { name: "نظرآباد", value: 6 },
      { name: "ساوجبلاغ", value: 4 },
      { name: "طالقان", value: 3 },
      { name: "فردیس", value: 2 },
      { name: "ماهدشت", value: 1 },
    ],
  },
];

// Helper function to get province data by Persian name
export function getProvinceDataByName(
  persianName: string
): ProvinceData | undefined {
  return mockProvinceData.find((province) => province.name === persianName);
}

// Helper function to get all province names
export function getAllProvinceNames(): string[] {
  return mockProvinceData.map((province) => province.name);
}
